### ISSUE TITLE
Starting OpenBangla-Keyboard error

### ISSUE THREAD

**Issue by ssi-anik** [OpenBangla/OpenBangla-Keyboard#10]
Whenever I search for open bangla keyboard on my dash, and try to run, it doesn't start. But when I try to run it from terminal, I get this error
```
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
```

**Comment by mominul** [comment]
Which Ubuntu version you are using?

**Comment by ssi-anik** [comment]
16.04

**Comment by ssi-anik** [comment]
Ok, so, I have to install that, and then the .deb?

**Comment by mominul** [comment]
Haven't you installed https://github.com/OpenBangla/OpenBangla-Keyboard/releases/download/1.2.0/OpenBangla-Keyboard-1.2.0-Linux.deb ? If you have, then you only have to initiate that command for fixing those issues you are facing.

**Comment by ssi-anik** [comment]
thanks brother. :)

**Comment by mominul** [comment]
If you have any further issue, please don't hesitate to post. For the time being I'm closing​ this issue.

**Comment by ssi-anik** [comment]
Still having the same problem. from dash, it's not opening. trying to open from terminal with `/usr/share/openbangla-keyboard/OpenBangla-Keyboard` shows
```/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)
/usr/share/openbangla-keyboard/OpenBangla-Keyboard: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /usr/share/openbangla-keyboard/OpenBangla-Keyboard)```

**Comment by mominul** [comment]
Please Uninstall OpenBangla Keyboard and install this https://github.com/OpenBangla/OpenBangla-Keyboard/releases/download/1.2.0/OpenBangla-Keyboard-1.2.0-Linux-Ubuntu16_04.deb
I have released this for Ubuntu 16.04

**Comment by ssi-anik** [comment]
Thanks. :)

**Comment by mominul** [comment]
You are welcome.
