### ISSUE TITLE
Space shifts before word

### ISSUE THREAD

**Issue by Ahsan113** [OpenBangla/OpenBangla-Keyboard#100]
ওয়ার্ড টাইপ করার পর স্পেস দিলে আগে স্পেস বসে। সব ধরনের প্রোগ্রামেই বাংলা লিখতে গেলে প্রব্লেমটা হচ্ছে। ইংরেজি তে হচ্ছে না। আমি লিনাক্স মিন্ট 19.1 ব্যাবহার করছি। ibus ভার্সন 1.5.17 

Same Issue appeared before. Here is the ibus-avro [Issue](https://github.com/sarim/ibus-avro/issues/111)

**Comment by mominul** [comment]
Have you tried the solution given in the issue? https://github.com/sarim/ibus-avro/issues/111#issuecomment-285863490

**Comment by Ahsan113** [comment]
ট্রাই করলাম। সাথে সাথে প্রব্লেম সলভ হয় নাই। রিস্টার্ট করার পর ঠিক হয়ে গেছে। ধন্যবাদ।

**Comment by mominul** [comment]
Welcome!

**Comment by EnigmaticJihad** [comment]
Sorry for writing in an old thread. I'm using Gentoo. I build IBus with `gtk3`, `gtk4` USE flag and `ibus-m17n` with `gtk` USE flag, but I'm having this problem.

**Comment by mominul** [comment]
Hi,
Are you using OpenBangla Keyboard? From your comment, it seems like you are using `ibus-m17n`. And why do you have to build ibus yourself?

**Comment by EnigmaticJihad** [comment]
I'm using both `ibus-m17n` and OpenBangla Keyboard. `m17n` for `unijoy (m17n)`. As Gentoo is a source-based distro I need to build everything with appropriate USE flags.
