### ISSUE TITLE
Provide a package repo.

### ISSUE THREAD

**Issue by ahmubashshir** [OpenBangla/OpenBangla-Keyboard#102]
Provide a package repo for debian and/or fedora.

**Comment by Adyel** [comment]
@ahmubashshir Maintaining a separate repository is a lot of boring work without much of benefit. Would you please explain why you want another repository?

**Comment by ahmubashshir** [comment]
For auto update,definately.

**Comment by bdeshi** [comment]
personally I think a package repo is a more conventional install path than the current "install.sh" solution.
setting up repos for each common distro will take the majority of the effort; afterwards updating them should be straight forward.

We already have source and binary packages on aur for arch and derivatives; I don't know much about other distros. What about pacakgecloud.io? iirc, @mominul used to use their service before they became premium, but apparently they still let opensource projects use their infrastructure for free.

**Comment by mominul** [comment]
I had considered this option much earlier with packagecloud, but we had reached the bandwidth limit of their free plan in one day :sweat_smile: Other options like using [launchpad](https://launchpad.net/) but it was quite complex and using different hosts was too much burden for me. So we had to choose this "install.sh" method.

But I have sent an email to packagecloud for supporting us as they do for other OSS projects, so we can hope for the best until their response comes :blush:

**Comment by ahmubashshir** [comment]
I hope the day will come.
