### ISSUE TITLE
Make Install command more streamlined

### ISSUE THREAD

**Issue by Adyel** [OpenBangla/OpenBangla-Keyboard#108]
Currently the URL and install command is too bulky. It's hard to understand and remember. I propose we make like command more memorable and shot. It also does not require you to switch to bash terminal to make it work. 
```bash
wget -nv -O- http://bit.ly/OBK-sh | bash
```
Please, provide your valuable feedback.

**Comment by bdeshi** [comment]
https? :grin:

**Comment by Adyel** [comment]
> https? 😁

Yes. Why not 💯 It also works with https
```bash
wget -nv -O- https://bit.ly/OBK-sh | bash
```

**Comment by mominul** [comment]
LGTM! :shipit:
