### ISSUE TITLE
Any suport for void linux

### ISSUE THREAD

**Issue by EmonHaque** [OpenBangla/OpenBangla-Keyboard#109]
I wanted to install it on Void Linux BUT it didn't work!

**Comment by mominul** [comment]
We don't provide installation package for Void Linux, so you have to compile and install it yourself. [Instructions are here.](https://github.com/OpenBangla/OpenBangla-Keyboard#compiling-on-gnulinux)

**Comment by EmonHaque** [comment]
@mominul , cmake .. outputs this:

-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/emon/Downloads/OpenBangla-Keyboard-master/build/CMakeFiles/CMakeOutput.log".

**Comment by EmonHaque** [comment]
Ok, I'd to install `MesaLib-devel` with: `

`sudo xbps-install -S MesaLib-devel`

and use this to make it work:

`cmake .. -DCMAKE_PREFIX_PATH=/home/myName/Qt5.13.0/5.13.0/gcc_64/lib/cmake`

Thanks!

**Comment by mominul** [comment]
Welcome!
