### ISSUE TITLE
Let users turn off preview box

### ISSUE THREAD

**Issue by fakeid30** [OpenBangla/OpenBangla-Keyboard#11]
I found that the preview box parses the data in some way that is blocking the redraw of the characters.

Please implement a toggle that can turn off the preview window.

**Comment by mominul** [comment]
The feature has been implemented and will be available in the next release! :tada: 

![screenshot from 2018-03-06 00-50-53](https://user-images.githubusercontent.com/9459891/36993596-7987f76a-20d8-11e8-90dc-2b0e35c7074b.png)
Thank you for asking this new feature!
