### ISSUE TITLE
Configuration with Xfce Desktop (Solved)

### ISSUE THREAD

**Issue by vagabondsajib** [OpenBangla/OpenBangla-Keyboard#111]
I was wondering if you guys can provide  a guide for configuration of **OpenBangla Keyboard**  with **Xfce Desktop.**

I am using **Mx Linux** with Xfce Desktop.

**From Jashore, Bangladesh**

**Comment by Adyel** [comment]
We are planning to add that to the wiki. 
But for now follow these steps : 

1. Install `OpenBangla-Keyboard` using the script
2. Search for `ibus preference` from whisker menu
3. Goto Input Method and Click Add
4. Select `Bengali` and then `OpenBangla Keyboard`
5. Log out and log in again

Now, you should be able to use OpenBangla Keyboard. Let us know if you still face any issue.
