### ISSUE TITLE
OBK bash script failed to identify Mx Linux 19

### ISSUE THREAD

**Issue by kuntalkundu** [OpenBangla/OpenBangla-Keyboard#119]
Any way to install OBK in Mx linux? Bash script can not identify the os.

**Comment by Adyel** [comment]
@kuntalkundu You can always build file manually. It's hard to support all distro. So this is the path we chose.

**Comment by mominul** [comment]
@Adyel Yeah, adding a new one wouldn't hurt 😊 But someone has to do it.😁
@kuntalkundu have you installed OBK using the packages we release?

**Comment by kuntalkundu** [comment]
after getting the failed identification message from terminal I have installed required packages like rust, qt4 etc manually as described. Later git clone the OBK and installed it. From synaptic I downloaded ibus and essential packages. But OBK only works on featherpad (test editor of xfce in mx linux). I checked locale, set it to US En, restart ibus, restaer session but result remain same. I think OBK should create a tutorial about installing it in Debian stable/MX linux 19. Installing OBK or Ibus in Ubuntu/Debian Sid is much easy. @mominul 
@Adyel I made it issue because instruction to report an issue about this type case is already mentioned in OBK github page. I just clicked on the said link.

**Comment by mominul** [comment]
@kuntalkundu MX linux is a Debian distribution, so the installation method should be similar. Can you elaborate on why you had to compile OBK? Just download the package from the [releases page](https://github.com/OpenBangla/OpenBangla-Keyboard/releases) and following the [instructions](https://github.com/OpenBangla/OpenBangla-Keyboard/wiki/Installing-OpenBangla-Keyboard#ubuntudebian-and-its-derivatives) would be enough.

**Comment by mominul** [comment]
We'll be releasing the new versions with bintray repository in the future. So there will be no need for an install script I think. Installation and updates can be performed using `apt` or other such tools.
