### ISSUE TITLE
Add option to show suggestion vertically 

### ISSUE THREAD

**Issue by Sobuj53** [OpenBangla/OpenBangla-Keyboard#120]
Hello altruist,
I'm using OBK in my Manjaro KDE. With some workaround I've managed to get it working in most of the applications. However I was unable to find any option to show suggestion vertically instead of horizontally. I'd request the developer of this great project to add an option which will give user the ability to select whether the suggestions will show vertically or horizontally.
Thanks

**Comment by mominul** [comment]
Hi,
You can change the orientation of the suggestion list in the Settings dialog:
![image](https://user-images.githubusercontent.com/4653623/43244281-f955f0b0-90cb-11e8-9dc4-a71dc4442009.png)

Thanks!
