### ISSUE TITLE
Add English Word Suggestion 🎯 🏁

### ISSUE THREAD

**Issue by bauripalash** [OpenBangla/OpenBangla-Keyboard#121]
While using OBK for some days and I have felt  that if it had option to add the English word i just typed , it would be really helpful. 

### Let me Explain : 
if I type **key** here i would see these suggestions `কী, কে, কই, কেয়, কয়েয়, ক্যায় ` , but what if I actually wanted to type the English word **key**. Then I have to go the top bar and change the input language to English. But it is definitely not a smooth experience . If we get the English word suggestion after the Bengali word suggestions (something like :  `কী, কে, কই, কেয়, কয়েয়, ক্যায় , key`) it would be really cool and make the experience lot more smooth.

**Comment by mominul** [comment]
A similar feature has been implemented, I have set a key binding(Default: Ctrl + T) will commit the English word:
![auxiliary text](https://user-images.githubusercontent.com/9459891/51424775-f6553a80-1bfc-11e9-901f-3f1c67d3fd53.gif)

But I am open to suggestions :blush:

**Comment by bauripalash** [comment]
That doesn't seem to be a good idea , with this any application's default keybinding will not work for example, if I try to do this in this comment, instead of a English word , my browser will open a new tab :(

**Comment by mominul** [comment]
Actually the key binding is configurable in the settings dialog.

I am also quite in favor of your idea of including it in the preview list, but I am confused about what approach should I take.

Any opinions? @Adyel @bdeshi @ahmubashshir @shakib609 @bauripalash

**Comment by ahmubashshir** [comment]
I prefer including it in preview list

**Comment by Adyel** [comment]
@mominul  I also like this idea. Including it on the preview list will be nice. 

1. We can show the English spelling at index 0, auto-suggestion will start pointing from index 1. This way user can type in phonetic and when s/he needs to switch to English, it's just one left arrow key away.

key, | কী |, কে, কই, কেয়, কয়েয়, ক্যায়
_____⬆
   Suggestion starts from here

2. Keep the current preview list, selecting up arrow will select the English word, left and right for auto-suggestion.

**Comment by mominul** [comment]
@Adyel The first proposal is really good! We can add an option for disabling this feature.
The second approach would make things complex, as we allow changing the orientation of the preview list. Vertical preview list uses Up and Down keys for navigating through the items.

**Comment by bdeshi** [comment]
(sorry for late comments.)

_@Adyel said:_
> 
> 1. We can show the English spelling at index 0, auto-suggestion will start pointing from index 1. This way user can type in phonetic and when s/he needs to switch to English, it's just one left arrow key away.
> >    key, | কী |, কে, কই, কেয়, কয়েয়, ক্যায়
> >    _____⬆
> > Suggestion starts from here
> 
That's okay, but if I may put a spin on the idea: placing the english suggestion as the very last option might be "semantically" better.

    | কী |, কে, কই, কেয়, কয়েয়, ক্যায়, key
     <-- left key loops back to this ^

that way, the more important Bangla suggestions are visible first, and a left arrow at the first suggestion cycles back to english suggestion.

**Comment by bauripalash** [comment]
@bdeshi , That's what I suggested at first. It will be more easy use..

**Comment by mominul** [comment]
This feature has been implemented by #124 ! :tada: 
Thanks to all of you who joined the conversation!

This feature will be available in the next version!
