### ISSUE TITLE
ভিজুয়াল স্টুডিও কোডে বাংলা ইনপুট দেওয়া যাচ্ছে না। 

### ISSUE THREAD

**Issue by rokib-rajon** [OpenBangla/OpenBangla-Keyboard#122]
ভিজুয়াল স্টুডিও কোডে ওপেনবাংলা কিবোর্ড থেকে বাংলা ইনপুট দিতে পারছি না। প্রভাত থেকে ঠিকই দেওয়া যায় কিন্তু ওপেনবাংলাতে আসে না কিছুই। 
আমি ওএস হিসাবে উবুন্টু স্টুডিও- 19.04 বাবহার করি। যার ইনভায়রনমেন্ট হচ্ছে xfce।

**Comment by mominul** [comment]
আপনি এই কমান্ডটি চালিয়ে vscode এ লেখার চেষ্টা করুন এবং আউটপুট সমূহ এখানে পোস্ট করুনঃ
```
/usr/share/openbangla-keyboard/ibus-openbangla
```

**Comment by rokib-rajon** [comment]
rajon@rajon:~$ /usr/share/openbangla-keyboard/ibus-openbangla
bash: /usr/share/openbangla-keyboard/ibus-openbangla: No such file or directory

কিছুই আসে না।

**Comment by mominul** [comment]
@rokib-rajon দুঃখিত! আসলে কমান্ডটি হবে এটি:
`/usr/share/openbangla-keyboard/OpenBangla-Engine`

**Comment by rokib-rajon** [comment]
@mominul Output এটা আসে 

[OpenBangla-Error]: [AutoCorrect]: Error: Couldn't open user specific AutoCorrect file!
QIODevice::read (QFile, "/home/rajon/.OpenBangla-Keyboard/autocorrect.json"): device not open
[OpenBangla-Info]: [IM:iBus]: Creating IM Engine
[OpenBangla-Info]: [IM:iBus]: IM enabled
[OpenBangla-Error]: [AutoCorrect]: Error: Couldn't open user specific AutoCorrect file!
QIODevice::read (QFile, "/home/rajon/.OpenBangla-Keyboard/autocorrect.json"): device not open

**Comment by mominul** [comment]
আপনি কমান্ডটি চালানো অবস্থায় ভিএসকোডে লেখার চেষ্টা করেছিলেন?

ভিএসকোড কি snap এর মাধ্যমে ইন্সটল করেছেন?

**Comment by rokib-rajon** [comment]
হ্যাঁ, তাও হয় না। 

ভিএসকোড স্নাপ এর মাধ্যমেই ইন্সটল করা

**Comment by mominul** [comment]
স্নাপ এর কারণে এ সমস্যা হতে পারে। তাই স্নাপের ভিএস কোড আনইন্সটল করে [deb ফাইল ডাউনলোড করে](https://code.visualstudio.com/#alt-downloads) ওটা দিয়ে ভিএস কোড ইন্সটল করে দেখুনতো সমস্যাটা থাকে কিনা?

**Comment by rokib-rajon** [comment]
ধন্যবাদ ! কাজ হচ্ছে এবার। :)

**Comment by mominul** [comment]
আপনাকেও ধন্যবাদ! 😊
