### ISSUE TITLE
স্পেস না চেপে এরো কি ইউজ করা যায় না

### ISSUE THREAD

**Issue by MJKSabit** [OpenBangla/OpenBangla-Keyboard#123]
কোনো ওয়ার্ড লেখার সময় তা শেষ করে স্পেস না চাপলে ডান-বাম এরো কি কাজ করে না, এরপর নতুন করে টগল না করা পর্যন্ত বাংলাও লেখা যায় না।

**Comment by mominul** [comment]
আপনি কি অভ্র ফনেটিক ব্যবহার করছেন? অভ্র ফনেটিক ব্যবহার কালে প্রিভিউ উইন্ডো প্রদর্শিত হয় এবং সেক্ষেত্রে ডান-বাম এরো কি সাজেশন আইটেমগুলো সিলেক্ট করার জন্য ব্যবহৃত হয়। স্পেস বা এন্টার কি চাপা না পর্যন্ত (অর্থাৎ লেখা কমিট করা না পর্যন্ত) এরো কি সিলেকশনের জন্যই ব্যবহৃত হয়।

> এরপর নতুন করে টগল না করা পর্যন্ত বাংলাও লেখা যায় না।

বাংলা লিখে স্পেস চাপার পর আর বাংলা লিখতে পারছেন না? বাংলা লিখতে হলে <kbd>Super + Space</kbd> চেপে টগল করে বাংলা লিখতে হচ্ছে?
আপনি কোন এডিটর / ওয়ার্ড প্রসেসর ব্যবহার করছেন?

**Comment by MJKSabit** [comment]
আমি অভ্র ফনেটিক ব্যবহার করছি।
 আমি প্রিভিও উইন্ডো বন্ধ রেখেছি, সেই হিসেবে এরো কি নরমালি কাজ করার কথা।
------------------------------------------------------------------------------------
এরো কি চাপার পর কিছুক্ষণ স্লো হয়ে সেই ওয়ার্ড চলে যায় এবং কিবোর্ড হিসেবে বাংলা থাকলেও ইংলিশ টেক্সট আসে।
পরে ২ বার টগল করে বাংলায় আসার পরে নরমাল হয়।

**Comment by mominul** [comment]
আমি ইস্যুটি রিপ্রডিউস করতে পেরেছি, এটি ১.৫.১ এর একটি বাগ। বাগটি মাস্টার ব্রাঞ্চে ফিক্স করা হয়েছে, অর্থাৎ নতুন ভার্সনে আর বাগটি থাকবে না। 

আপনি চাইলে মাস্টার ব্রাঞ্চ থেকে কম্পাইল করে চালাতে পারেন, ইন্সট্রাকশন [এখানে দেয়া](https://github.com/OpenBangla/OpenBangla-Keyboard#compiling-on-gnulinux) আছে।
