### ISSUE TITLE
Word broken and disappears

### ISSUE THREAD

**Issue by ssi-anik** [OpenBangla/OpenBangla-Keyboard#13]
writing `ei` doesn't show the correct word. colons are not working (বিসর্গ). missing after a word written.

**Comment by ssi-anik** [comment]
`Linux Sirajul 4.10.0-041000-generic #201702191831 SMP Sun Feb 19 23:33:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by ssi-anik** [comment]
Just a reminder, did you get notified?  😛

**Comment by mominul** [comment]
Sorry for not replying 😅 I am currently busy with my education so I won't be able to work on this project for now.
But for বিসর্গ it won't appear if it's immediately previous character is a number like '1:2' so বিসর্গ would not appear.
After my exams end, I would be eager to hold a conversation to solve this issue.
Thanks

**Comment by ssi-anik** [comment]
Actually, while using Facebook the whole word disappears tho the previous word is not a number.

**Comment by ssi-anik** [comment]
`e.*` all the words are broken
ekdin
eivabe
emone

**Comment by ssi-anik** [comment]
I uninstalled the app and again started using it. :(

**Comment by mominul** [comment]
Oh sorry for the delay. Because I was busy on giving my SSC exam, so I couldn't work on this project...

**Comment by mominul** [comment]
`I uninstalled the app and again started using avro.`
When you are using ibus-avro does the bug occur?

**Comment by mominul** [comment]
I am closing this issue for now, if you have anything to discuss please post here.
