### ISSUE TITLE
Ibus ছাড়া ফোনেটিক লেআউট এ টাইপ করবো কিভাবে?

### ISSUE THREAD

**Issue by hmsharif1998** [OpenBangla/OpenBangla-Keyboard#133]
Ibus ছাড়া লিনাক্স মিন্ট এ ফোনেটিক টাইপ করার কোন উপায় আছে? বর্তমানে তো provat লে আউট সেখানে এভেইলেবল। আমি কি সেখানে ফোনেটিক লেআউট অ্যাড বা রিপ্লেস করতে পারবো? যদি হ্যাঁ হয় তাহলে সেটা কিভাবে?

**Comment by mominul** [comment]
ওপেনবাংলা কিবোর্ডেই ফনেটিক লেয়াউট দেয়া আছে। তবে আপনি যদি ওপেনবাংলা কিবোর্ড ব্যবহার না করতে চান তাহলে আপনাকে [ibus-avro](https://linux.omicronlab.com/) ব্যবহার করতে হবে।
