### ISSUE TITLE
OpenBangla installation for debian

### ISSUE THREAD

**Issue by abhijitlimit** [OpenBangla/OpenBangla-Keyboard#134]
the following code does not work for my debian distribution

    wget -nv -O- https://bit.ly/OBK-sh | bash

**Comment by mominul** [comment]
Can you please post the output of this command?

**Comment by mominul** [comment]
@abhijitlimit can you try again please? A fix has been committed.

**Comment by mominul** [comment]
Open your terminal and run this command to install on your shell:
```
bash -c "$(wget -nv -O- https://bit.ly/OBK-sh)"
```
