### ISSUE TITLE
OpenBangla-Keyboard is not working on Elementary OS 5.1 (Hera) 

### ISSUE THREAD

**Issue by githubusersb** [OpenBangla/OpenBangla-Keyboard#138]
![image](https://user-images.githubusercontent.com/37740345/79131267-f1624500-7dc5-11ea-9411-7b469e3fea84.png)
Clicked on **Input Method Settings...**
![image](https://user-images.githubusercontent.com/37740345/79130724-15715680-7dc5-11ea-8a18-90cb0de958f1.png)
![image](https://user-images.githubusercontent.com/37740345/79131159-be1fb600-7dc5-11ea-956b-592120d43861.png)

I can switch between English and OpenBangla using the keyboard shortcut given in the picture, but it is always writing in English.

Following ibus processes are running

 6075 ?        00:00:00 ibus-daemon
 6088 ?        00:00:00 ibus-dconf
 6090 ?        00:00:00 ibus-ui-gtk3
 6093 ?        00:00:00 ibus-x11
 6101 ?        00:00:00 ibus-portal
 6240 ?        00:00:00 ibus-engine-sim

**Comment by Adyel** [comment]
You need to change the Input Engine. Please follow these instruction mention here: [Elementary OS Q/A](https://elementaryos.stackexchange.com/questions/2371/how-can-i-use-ibus-as-the-default-input-method)

**Comment by githubusersb** [comment]
Thank you @Adyel this resolved the issue. Many thanks.
