### ISSUE TITLE
Bangla Word is not showing while Using Office Application

### ISSUE THREAD

**Issue by MJKSabit** [OpenBangla/OpenBangla-Keyboard#139]
I use **WPS Office** as MS Office substitute in Linux.

Although Open Bangla Keyboard works fine with Libre Office, I haven't found any other Office with MS Office like interface where Open Bangla Keyboard works fine.

**Bugs**
1. Words not showing before I press space [Image](https://pasteboard.co/J40HkYQ.png)
2. Space comes before, not after the word [Image](https://pasteboard.co/J40JCY9.png)
3. Popup window shows (without bangla font) what is gonna be written I think (I'm not sure, as I can not read bangla without bnagla font) [Image](https://pasteboard.co/J40HkYQ.png)

**Observation**
1. Pop-up Window dissapears with the text written in the Word Processor after I pressed Alt Key.
2. I think space is written, then the pop-ed up text written. For example, when I write [আমি?] and press space then it prints [ আমি?]

**Comment by mominul** [comment]
OpenBangla Keyboard uses iBus input method framework. WPS office has been known [to not work with iBus](https://github.com/ibus/ibus/issues/1753). So [You have to run ibus-daemon with '--xim' option for the workaround:](https://github.com/ibus/ibus/issues/1753#issuecomment-104884782)
```
ibus exit
ibus-daemon --xim &
```

**Comment by MJKSabit** [comment]
I have encountered problems writing Bangla in many Office Suites, like
**OnlyOffice**
![Only Office](https://user-images.githubusercontent.com/53174310/79450651-fcf07e80-8006-11ea-9d5c-dd47836161e5.png)
**Softmaker FreeOffice**
![SoftmakerFree Office](https://user-images.githubusercontent.com/53174310/79451234-04fcee00-8008-11ea-9160-fcaff4f8b39b.png)

**Comment by MJKSabit** [comment]
Okay, I have found out that I can customize UI of LibreOffice to look like MS Office
As I haven't encountered any problem writing Bangla in **LibreOffice**, you can close this issue.
  
![LibreOffice](https://user-images.githubusercontent.com/53174310/79453396-79855c00-800b-11ea-8234-8618c372c538.png)
  
Thank you.

**Comment by mominul** [comment]
That's good!
It looks like OnlyOffice and Softmaker FreeOffice has issues with Indic language rendering. If you want to get it fixed, you have to report it to them.

Thanks!
