### ISSUE TITLE
Unable to type Bangla on Fedora 26

### ISSUE THREAD

**Issue by buddhaspake** [OpenBangla/OpenBangla-Keyboard#14]
With OpenBangla keyboard started and gedit open, typed text does not change to Bangla.
I am not sure if there is a toggle for Bangla/English typing, but for me changing the input method has no effect.

### System Details:
**OS:** Fedora 26
Installation: Compiled from source.
Hardware: Macbook Air 2015
OS Configuration: MacOS/Fedora 26 dual boot.

*I'd be happy to provide any additional detail/log which you may need.*

**Comment by mominul** [comment]
You have to add OpenBangla Keyboard to Input Method source list. I don't know how to do this in fedora but you can do it in Ubuntu like [this](https://github.com/OpenBangla/OpenBangla-Keyboard/wiki/Installing-OpenBangla-Keyboard#setup-openbangla-keyboard). Fedora might have a  system like that.

**Comment by mominul** [comment]
@fakeid30 Can you help here?

**Comment by buddhaspake** [comment]
Thanks, my bad, I should have checked the wiki. I will check how to change
this in fedora, and get back if i have questions.

**Comment by mominul** [comment]
No problem! 😉

**Comment by fakeid30** [comment]
@mominul @buddhaspake this process is controlled by iBus and is same in any Linux (adding input method).

I've seen some applications do not register input method (Chrome application framework based apps, like Spotify). But that's app specific problem.

**Comment by mominul** [comment]
@fakeid30 sorry for giving you worries, yes I know that. But I thought fedora might have another frontend to do so(adding a Input Method) like Ubuntu has 'Text Entry Settings'. I haven't yet tested fedora so I asked you about that.

Thanks for your explanation!

**Comment by fakeid30** [comment]
No worries , cheers.
