### ISSUE TITLE
Custom Layouts

### ISSUE THREAD

**Issue by cybarspace** [OpenBangla/OpenBangla-Keyboard#140]
How can I make my own layouts?
I see a button to add custom layouts, but what kind of a file do I need to make and what do I need to put in it? Any syntax guide or such please?
I'd like to make a fixed layout.

**Comment by mominul** [comment]
OpenBangla Keyboard supports importing Avro Keyboard's Keyboard layouts. There's a layout editor comes bundled with Avro Keyboard and you have to use it as we don't have a layout editor yet.

But you can do it manually by editing the layout file used by OBK. Actually the layout file is a json formatted file. You can [use this](https://github.com/OpenBangla/OpenBangla-Keyboard/blob/master/data/Bornona.json) as a template and edit it to your need. You must change the `name` value and it's file name so it doesn't mix with other layouts:
https://github.com/OpenBangla/OpenBangla-Keyboard/blob/7302ebb47e35aea68bf10a22b3217bb1256ef65a/data/Bornona.json#L10
Then you have to change the key values you need to change:
https://github.com/OpenBangla/OpenBangla-Keyboard/blob/7302ebb47e35aea68bf10a22b3217bb1256ef65a/data/Bornona.json#L16-L220

After that, you have to place the file into `$HOME/.OpenBangla-Keyboard/Layouts/` directory.

Now you should be able to use it from selecting it in the TopBar.

Good luck!

**Comment by cybarspace** [comment]
@mominul Ok, I'll try that. Thanks. :smiley:

**Comment by cybarspace** [comment]
@mominul I got my answer, but just asking out of curiosity. Will OBK ever come with a built-in layout editor ? Is it planned, or not even considered ?

**Comment by mominul** [comment]
Yeah, we have the intention to do so. 😅

Thanks!
