### ISSUE TITLE
Remove Update Notification Feature

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#144]
Currently, we have an Update Notification feature. As we are approaching towards releasing new releases through the Bintray repository, I don't think this feature is necessary anymore!

So, I intend to remove this feature.

cc @Adyel @bdeshi

**Comment by bdeshi** [comment]
can be useful for windows/mac builds. maybe just disable the functionality in linux.

**Comment by Adyel** [comment]
I also agree. We must have it for Windows and Mac because they don't update 3rd party software like linux does.

**Comment by mominul** [comment]
Ah, thanks for the inputs! I really forgot about windows and macOS :sweat_smile:
