### ISSUE TITLE
Cmake build error while building project. No CmakeLists.txt in folder 'riti'

### ISSUE THREAD

**Issue by git-aniket** [OpenBangla/OpenBangla-Keyboard#147]
![Screenshot from 2020-05-22 09-41-04](https://user-images.githubusercontent.com/31139836/82643872-9f0c1380-9c10-11ea-94e0-9e7bb5a8f805.png)

**Comment by mominul** [comment]
You have clone the repo with the `--recursive` flag:
```
git clone --recursive https://github.com/OpenBangla/OpenBangla-Keyboard.git
```

**Comment by git-aniket** [comment]
Thanks that worked.
