### ISSUE TITLE
Not working in Telegram Desktop app in Kubuntu 18.04

### ISSUE THREAD

**Issue by ZunaedSifat** [OpenBangla/OpenBangla-Keyboard#149]
Hello,
In my Kubuntu 18.04 installation, whenever I write on Telegram desktop app, I get English output. However, if I just change the window and go somewhere else, I get Bangla output as expected. I am not sure whether the problem is caused by any bug by OpenBangla Keyboard or Telegram Desktop app though.

Thanks for building this great piece of software! :smiley:

**Comment by mominul** [comment]
Hi, thanks!
This kinds of problem happen if the software is installed by snap or flatpak. Have you installed the app using one of those?

**Comment by ZunaedSifat** [comment]
Nah. I first installed the app from Ubuntu Software Center using `sudo apt install telegram-desktop` command. After I faced the problem, I uninstalled it and I downloaded the executable file directly from telegrams website. Even in that case the problem persisted.

**Comment by mominul** [comment]
I am afraid that [it's a bug](https://github.com/telegramdesktop/tdesktop/issues/2013) of the Telegram desktop app. I've seen some solutions mentioned there, can you try those please?
