### ISSUE TITLE
Manual: How to Change Keyboard Layout (other than Phonetic)

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#15]
There should be a wiki entry explaining how to select/change keyboard layouts. Though its very easy to change keyboard layout but novice users might need it.

As @ashrafbd pointed out.

There is a WIP wiki [entry](https://github.com/OpenBangla/OpenBangla-Keyboard/wiki/How-to-Select-Keyboard-Layout-(other-than-Phonetic)-on-Ubuntu-Linux).

Anyone want to help out?

**Comment by Adyel** [comment]
Ok, Done. I need some feedback. Was the Wiki clear enough? # #

**Comment by mominul** [comment]
আপনার এডিট গুলো চমৎকার হয়েছে ভাইয়া! :sparkling_heart: Configure-on-Gnome-DE টা দারুণ হয়েছে :100: । চালিয়ে যান! :+1:
