### ISSUE TITLE
AltGr for Fixed layout

### ISSUE THREAD

**Issue by mh0s41n** [OpenBangla/OpenBangla-Keyboard#152]
Hi. I'm currently using National Layout. AltGr is required for few letters. Usually AltGr is mapped to right Alt in other keyboards (Keyboards made by Ekushey for Windows or built-in National layout in Linux, for example). But OpenBangla seems to use Ctrl + Alt which is inconvenient. Avro for windows has this feature.

Could you map right Alt to AltGr for fixed layouts? (I tested both, latest release and latest build from source)

**Comment by mh0s41n** [comment]
OpenBangla has so many features which simply I don't need. My plan was to use a layout I created myself. I've already built it in Windows using Microsoft Keyboard Layout Creator. For Linux, I thought I'd use OpenBangla. But OpenBangla seems uses something "Avro Keyboard 5 Keyboard Layout" for custom layout about which I have no idea nor found any guide in OmicronLab. So, I'll use native X11 input system in Linux.

Although the AltGr issue is an issue (minor, as not many people uses fixed layout), developers can consider to fix it. But, as the issue is solved for me, I'm closing it. **বাংলা ছড়িয়ে পড়ুক সবখানে।**

**Comment by mominul** [comment]
Hi,
You're right that we map Ctrl + Alt to AltGr as we followed Avro Keyboard's behavior in this matter. I haven't used other software to write Bangla other than Avro so I really didn't knew that the right Alt key is mapped to be AltGr on input methods. I'll look further into this matter.

For you other question, to make a custom layout you will have to use the layout creator comes with Avro Keyboard for Windows. [Here is a documentation](https://www.omicronlab.com/download/pdf/Editing%20Keyboard%20Layout.pdf) regarding the use of the layout creator.

Thanks!

**Comment by mh0s41n** [comment]
Thanks for the response and reopening. As of my past experience, Avro also maps AltGr to right Alt. Possibly Avro uses Ctrl + Alt and right Alt both for AltGr! I used Avro in Windows. I can't tell about ibus-Avro in Linux.

**Comment by mominul** [comment]
This feature has been implemented! :tada: It'll be available in the next version!
