### ISSUE TITLE
topbar problem

### ISSUE THREAD

**Issue by saifulsz** [OpenBangla/OpenBangla-Keyboard#153]
I drag the file to topbar then it can't be hide or click or no other circumstances. I tried to delete and install again but it can't be drag to anywhere or click on this. that's irritating for me. Please solve.

![image](https://user-images.githubusercontent.com/49592334/87110677-6c35e180-c289-11ea-9694-0b337b2983e7.png)

**Comment by mominul** [comment]
Hi,
You have to delete the configuration file of OpenBangla Keyboard using this command:
```
rm -rf ~/.config/OpenBangla
```
This should solve the problem.

I am really sorry for replying this late!
