### ISSUE TITLE
Unable to establish SSL connection.

### ISSUE THREAD

**Issue by faisal95bd** [OpenBangla/OpenBangla-Keyboard#156]
I want to install OpenBangla Keyboard on my Linux Mint 20.
But when I enter this command in my terminal:  bash -c "$(wget -nv -O- https://bit.ly/OBK-sh)"
I receive this: Unable to establish SSL connection.

**Comment by mominul** [comment]
@bdeshi @Adyel @ahmubashshir

**Comment by Adyel** [comment]
This is not issue on our end. Your OS / library issue. Download without certificate `--no-check-certificate`. 
Also, you can try to reinstall certificates.
`sudo dnf reinstall crypto-policies`

You can follow steps mentioned here too [Link](https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues/10)
