### ISSUE TITLE
RFC: Show the selected layout name in the TopBar

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#158]
# Request for comments!
I am thinking of showing the selected layout name in the TopBar like this:
![display text topbar](https://user-images.githubusercontent.com/9459891/92156150-618f6700-ee4a-11ea-9da7-afdaf5a444ca.png)

Does anyone have objections or requests? Please comment!

cc: @Adyel @bdeshi @ahmubashshir

**Comment by Adyel** [comment]
Looks good to me but I'm more in favor of toolbar with changing icon. If we can integrate TopBar with the OS toolbar it will look more clean.

**Comment by mominul** [comment]
Yeah, my intention is also the same. But currently, I am having problems with adding the systray bar(OS toolbar) entry for OBK TopBar. I think it's because of Qt having bugs with the systray handling. :disappointed:

**Comment by Adyel** [comment]
I think its time to move to GTK. It has great binding for rust too. Lot of work but worth it for the ecosystem.

**Comment by ahmubashshir** [comment]
> I think its time to move to GTK. It has great binding for rust too. Lot of work but worth it for the ecosystem.

Then, I would be able to help out too...

**Comment by Adyel** [comment]
I think we should give it a try and lets see where it goes @mominul .

**Comment by mominul** [comment]
If we do this I think we should use the upcoming GTK 4 release. It has some compatibility paper cuts removed and also focusing on having API stability.
