### ISSUE TITLE
replace bit.ly installation shortlink

### ISSUE THREAD

**Issue by bdeshi** [OpenBangla/OpenBangla-Keyboard#160]
bit.ly is inaccessible [from some areas in] BD. the shortlink in the install command should be changed to ensure broader availability of the install procedure.

**Comment by ahmubashshir** [comment]
> bit.ly is inaccessible [from some areas in] BD. the shortlink in the install command should be changed to ensure broader availability of the install procedure.

We can use [this](https://git.io/JUGB8) git.io shortlink.
