### ISSUE TITLE
Installation error in Mx Linux 19.2 xfce

### ISSUE THREAD

**Issue by kuntalkundu** [OpenBangla/OpenBangla-Keyboard#162]
after changing directory to Openbangla keyboard when I run cmake from terminal this errors are showing 
CMake Error at src/engine/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    /home/kuntal/Downloads/OpenBangla-Keyboard-master/src/engine/riti

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by ahmubashshir** [comment]
> after changing directory to Openbangla keyboard when I run cmake from terminal this errors are showing
> CMake Error at src/engine/CMakeLists.txt:8 (add_subdirectory):
> The source directory
> 
> ```
> /home/kuntal/Downloads/OpenBangla-Keyboard-master/src/engine/riti
> ```
> 
> does not contain a CMakeLists.txt file.
> 
> -- Configuring incomplete, errors occurred!

Run:
```sh
git submodule init
git submodule update --recursive
```

**Comment by kuntalkundu** [comment]
it's now solved.
