### ISSUE TITLE
Good initiative to the quick solution to write র‌্য but few issues already created after that

### ISSUE THREAD

**Issue by kuntalkundu** [OpenBangla/OpenBangla-Keyboard#163]
when I going to type কার্য in probhat layout (fixed layout) it's automatically forming কার‌্য. Turning off word suggestion or anything doesn't solving the problem. I think their is no need to add word suggestion in fixed layout typing, it's better match wit hphonetic. Otherwise it's reducing the typing speed, because few words automatically type the first suggestion, it's very embarrasing. Suppose I want to type যদিও but output automatically delivered as যদিওবা। It could be a huge problem during any important document typing.

**Comment by mominul** [comment]
> Otherwise it's reducing the typing speed, because few words automatically type the first suggestion, it's very embarrasing. Suppose I want to type যদিও but output automatically delivered as যদিওবা। It could be a huge problem during any important document typing.

I have just added a fix to make the user's written word to be the first suggestion(It'll be written as default). So it's now on the user to select a different suggestion.
To get this update, you'll have to download the source code(like how I guided you in FB), compile and install again.

> when I going to type কার্য in probhat layout (fixed layout) it's automatically forming কার‌্য.

I have to investigate further about this. Does Provat have a key for writing Reph? Did the previous version of OBK had this bug?

**Comment by kuntalkundu** [comment]
The previous version of Obk doesn't have such problem during writing reph. Yes Probhat has ZWJ and ZWNJ (zero width non joiner) key. Please download probhat layout from Google image search, you can see those key on left top corner (top of caps lock) and on right side (beside [}). Those key are use to prevent র‌্য> র্য. 

And I'm gonna to overwritten the compiling to checking the fixation of the said bug. 😊

**Comment by kuntalkundu** [comment]
yes, after reinstalling the automatic forming of words from first suggestion has been stopped. but the 1st bug I mentioned, the reph issue...now gving different output (see in screenshot)
![Screenshot_2020-09-10_09-25-40](https://user-images.githubusercontent.com/28354301/92680246-0a0c6200-f348-11ea-8a8f-c9a1c788a4cd.png)

**Comment by mominul** [comment]
এই বাগটির সমাধান করা হয়েছে! :tada: 
এখন থেকে প্রভাত লেআউটে:
`র্য` লিখতে <kbd>র</kbd> + <kbd>্</kbd> + <kbd>য</kbd> টাইপ করতে হবে 
`র‍্য` লিখতে <kbd>র</kbd> + <kbd>ZWJ</kbd> + <kbd>্</kbd> + <kbd>য</kbd> টাইপ করতে হবে
আর অন্যান্য লেআউটে আলাদা করে রেফ ও য-ফলা দেয়া রয়েছেই।

ধন্যবাদ @kuntalkundu কে বাগটি রিপোর্ট করার জন্য!
