### ISSUE TITLE
Add official Debian builds

### ISSUE THREAD

**Issue by Anan5a** [OpenBangla/OpenBangla-Keyboard#166]
Can you add Debian builds? Ubuntu xx builds cannot be installed. (dependency version problems)

Or can you suggest how to build from source? 
OS: Debian 10 buster

**Comment by mominul** [comment]
Hi, we have updated our infrastructure to build packages for Debian. So from the next version, we'll start distributing `.deb`s for Debian. 
[Here is the deb file for Debian 10 buster](https://bintray.com/api/ui/download/openbangla/debian/OpenBangla-Keyboard_1.5.1-debian10-buster.deb)
