### ISSUE TITLE
Request to add English word suggestion to fixed layout also

### ISSUE THREAD

**Issue by kuntalkundu** [OpenBangla/OpenBangla-Keyboard#170]
recently I have watched a demo video on OpenBangla keyboard official facebook page which was showing a new feature of upcoming Openbangla Keyboard that will show english word suggestion along with bangla words in suggestion floating window. I assume that it is integrated with phonetic layout. My request to devs is to add the same feature to the word suggestion window of fixed layout also.

**Comment by mominul** [comment]
This feature has been implemented and will be available in the next 3.0.0 version! :tada:

**Comment by kuntalkundu** [comment]
খুব ভালো খবর এটা!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
