### ISSUE TITLE
Slows Down with 2-3 page document

### ISSUE THREAD

**Issue by cgvirus** [OpenBangla/OpenBangla-Keyboard#174]
Hello, thank you all the devs for this beautiful and essential app.
Issue:
After some recent updates on GNOME (3.36.4), Open Bangla seems to be slowing down with more than 1 page long document. It slows down specifically while auto suggestion menu pops up.
Tried apps:
1. Libre Writer
2. VSCode

Thanks.

OS Debian 10 (Bulleyes/Sid)
Gnome 3.36.4

**Comment by mominul** [comment]
Which version of OpenBangla Keyboard you have installed?

Thanks for your kind words 😊

**Comment by cgvirus** [comment]
Hello it is 1.5.1.
BTW I will try it with cinnamon as well in some days soon. I think it is a problem with Ibus, as Ibus and Gnome had frozen once while I was typing in VSCODE. Had to do a hard reset then.

**Comment by mominul** [comment]
Ah, Ok. How about I close this issue for now? I also think that it might be because of ibus or related system settings.
We have just released 2.0.0 version, so try it when you have reinstalled or fixed your system.

Thanks!

**Comment by cgvirus** [comment]
Alright Thanks. I will let you know if the problem rises again or I can debug. Thanks for your hard work folks. Best Wishes. :)
