### ISSUE TITLE
Problem in installation to linux mint 20

### ISSUE THREAD

**Issue by Saumen95** [OpenBangla/OpenBangla-Keyboard#176]
I have tried to install openbangla to a mint 20 machine using ubuntu instructions.on execution of third command(before running sudo apt update),it returns malformed line 1 at openbangla source list.

What can I do now?

**Comment by Saumen95** [comment]
I have installed via .deb package and it worked.However I think ubuntu instructions have some issues.so keeping this issue open

**Comment by Saumen95** [comment]
@mominul

**Comment by mominul** [comment]
You have to execute `source /etc/os-release` before downloading the source list using `sudo sh -c "curl https://dl.bintray.com/openbangla/i/ubuntu.conf | sed s/@NAME@/$UBUNTU_CODENAME/ > /etc/apt/sources.list.d/openbangla.list"` otherwise the source list would become malformed.
