### ISSUE TITLE
compiling on opensuse

### ISSUE THREAD

**Issue by darkkingredian** [OpenBangla/OpenBangla-Keyboard#177]
it's not a issue. just a suggestion for opensuse users
maybe the developers can add opensuse to readme
you have to install this packages before compiling
libQt5Core-devel libQt5Widgets-devel libQt5Network-devel libzstd-devel libzstd1 cmake make ninja rust ibus-devel ibus clang gcc
and base development pattern
tested on opensuse tumbleweed kde

**Comment by mominul** [comment]
Thanks! Can you create a PR with the instructions added in the README.md file?

**Comment by darkkingredian** [comment]
sorry i don't have any experience with git yet

**Comment by ahmubashshir** [comment]
I'll do it then

**Comment by ahmubashshir** [comment]
Required packages are

**Comment by darkkingredian** [comment]
> I'll do it then.
> Required packages are
> 
> ```
> libQt5Core-devel libQt5Widgets-devel libQt5Network-devel libzstd-devel libzstd1 cmake make ninja rust ibus-devel ibus clang gcc
> ```
> 
> Am I correct? notify me if something is missing...

add this patterns-devel-base-devel_basis

**Comment by ahmubashshir** [comment]
Done... check the docs on detached head

**Comment by darkkingredian** [comment]
> Done... check the docs on detached head [81b2406](https://github.com/ahmubashshir/OpenBangla-Keyboard/tree/81b24066f6da17a6fce3e617d86537f774be669d)

You didn't add sudo like the others

**Comment by ahmubashshir** [comment]
Oops... sorry

**Comment by ahmubashshir** [comment]
[b8c2d2](https://github.com/ahmubashshir/OpenBangla-Keyboard/tree/b8c2d28379472e1e50430558d3eb50cb4038041d)

**Comment by ahmubashshir** [comment]
BTW, @mominul checkout the commit message of b8c2d28379472e1e50430558d3eb50cb4038041d

**Comment by darkkingredian** [comment]
The devs are fast
