### ISSUE TITLE
add solus to readme compiling guide

### ISSUE THREAD

**Issue by darkkingredian** [OpenBangla/OpenBangla-Keyboard#179]
To compile on solus you have to install this packages
`sudo eopkg install -c system.devel rust qt5-base-devel ibus-devel zstd-devel git cargo gtk2-engine-murrine`

tested on solus budgie

**Comment by ahmubashshir** [comment]
Thanks... I'll add it in readme right away.

**Comment by ahmubashshir** [comment]
btw, why gtk2 murrine? afaik, OBK right now doesn't depend on gtk+ (2/3).

**Comment by darkkingredian** [comment]
> btw, why gtk2 murrine? afaik, OBK right now doesn't depend on gtk+ (2/3).

Dunno when i tried to open it didn't launch
In terminal it asked for murrine. Maybe because i was using older version of qt
Let me check again

**Comment by darkkingredian** [comment]
![Uploading IMG_20201027_145429.jpg…]()
Maybe theme problem

**Comment by darkkingredian** [comment]
Maybe you can remove murrine from dep
