### ISSUE TITLE
Make this "snap" ?

### ISSUE THREAD

**Issue by Adyel** [OpenBangla/OpenBangla-Keyboard#18]
Snap applications are easily distributable to all snap supported platform. If you can make this program a snap package you will be able to catch a wider audience.  Can you please do that? I am no expert but from what I saw (from YT video/article), making snap package is not that complicated.

You can look for details here: https://snapcraft.io/

Last but not least, thanks for presenting us with this great application. :)

**Comment by mominul** [comment]
@Adyel Yes, I am thinking about this too! 
I agree that making snap package is not that complicated, but I think packing OpenBangla Keyboard as a snap is complicated. Snap applications are sandboxed. So they don't have enough permissions to access `/usr/` folder. But Input methods such as OpenBangla Keyboard needs to place a xml file in `/usr/share/ibus/component/` folder. Though I haven't tried anything, I think this is the main issue.

I am thinking to have a discussion at snapcraft [forums](https://forum.snapcraft.io/) about this issue.

Thank you for using OpenBangla Keyboard!

**Comment by Adyel** [comment]
I think using `--classic` confinement will give you enough flexibility, According to doc : 

> **# classic**
> A snap in classic confinement behaves as a traditionally packaged application, with full access to the system. As opposed to strict and devmode, what a classic snap sees as “/” is the host system’s “/” and not the core snap’s “/”. Snaps using this fully open security policy are manually reviewed in the Snap Store and are only allowed on systems where snapd is installed on top of a traditional Linux distribution, as opposed to system booting from an Ubuntu Core image. They can be released in all Snap Store channels.

**Comment by mominul** [comment]
Yes, that might work.
For now I am planning about starting the snap work in a new branch but it will need sometime to do so. But should I start the work before releasing version 1.3.0 or after, thats an open question to me ... :thinking:

**Comment by Adyel** [comment]
In my opinion, you should focus on releasing the newer version. Also, I suggest you should create a milestone in the repo. It will help people to understand where is the project moving. I will try to contribute to the Wiki.
Oh, almost forgot, the primary user of this application will be Bengali. Would it not be better if the Wiki was in Bengali?

**Comment by mominul** [comment]
Thank you for your reply!
I have done some work in the Deb and RPM packaging section, so new version will support RPM based distributions also. I am thinking deploying rpm and deb packages to https://packagecloud.io/ so users would be able to install and update OpenBangla Keyboard easily.
> I suggest you should create a milestone in the repo.

I will try it, thanks!
> Oh, almost forgot, the primary user of this application will be Bengali. Would it not be better if the Wiki was in Bengali?

It would be better! You can start writing wiki in Bangla. I will suggest you to contribute to issue #15 . It was asked by an user.

Thanks!

**Comment by mominul** [comment]
[This is not possible.](https://forum.snapcraft.io/t/is-packaging-ibus-engines-possible/12807/2) 😔
