### ISSUE TITLE
Installation কমান্ড ভুল লেখা আছে।

### ISSUE THREAD

**Issue by gitSaptarshi** [OpenBangla/OpenBangla-Keyboard#181]
Fedora -র installation command এ প্রথম কমান্ডের sudo বানানটি ভুল দেওয়া আছে। ওটি `sudo` হবে কিন্তু ভুল করে `sudp` টাইপ করা হয়ে গেছে। এটা একটু সংশোধন করে নেবেন শীঘ্রই।

 একটি স্ক্রীনশট আপনাদের সুবিধার জন্য দিয়ে দিলাম নিচে।
![Screenshot from 2020-10-28 18-51-31](https://user-images.githubusercontent.com/37685073/97443231-cfd73e00-1950-11eb-9e46-650b8d272f00.png)

**Comment by mominul** [comment]
ধন্যবাদ! :blush:
