### ISSUE TITLE
উইকিটা আপডেট করতে চাই 

### ISSUE THREAD

**Issue by linuxvai** [OpenBangla/OpenBangla-Keyboard#186]
উইকিতে অনেকগুলো টিউটোরিয়াল রয়েছে যেগুলো ইংরেজিতে দেয়া আছে, সেগুলো বাংলাতে রূপান্তর করতে চাই। এছাড়া সিনামন ডেস্কটপে কীভাবে কনফিগার করতে হবে, তা দেয়া নেই। এইটাও যোগ করতে চাই। কীভাবে F12 কে শর্টকাট কী হিসেবে সেট করতে হয় তা যোগ করতে চাই। এছাড়া আরো অন্যান্য অনেক কিছু যেমন স্টার্টাপ এপ হিসেবে আইবাসকে সেট করা ইত্যাদি জগ করতে চাই।

**Comment by mominul** [comment]
নিশ্চয়ই করতে পারবেন! 😊

**Comment by ahmubashshir** [comment]
@linuxvai https://ahmubashshir.github.io/post/2020/11/24/ibus-setup

**Comment by mominul** [comment]
Please use  [Discussions](https://github.com/OpenBangla/OpenBangla-Keyboard/discussions) if you have any further inquiries.
