### ISSUE TITLE
ট্র‍্যাডিশনাল কার জয়েনিং কাজ করে না

### ISSUE THREAD

**Issue by dd4854** [OpenBangla/OpenBangla-Keyboard#189]
ওপেনবাংলা কিবোর্ড ইন্সটল করে বিজয় লেয়াউট সেটআপ করেছি। তাতে এখন লেখা যায়। কিন্তু া বা ে দিতে গেলে অক্ষর লেখার পরে দিতে হয়। ট্র‍্যাডিশনাল কার জয়েনিং অন অফ করে দেখেছি। কোন কাজ হয় না।

OS: Lubuntu 20.04 LTS

**Comment by mominul** [comment]
ট্র্যাডিশনাল কার জয়নিং বলতে বর্ণের আগে কার বসানোর ফিচারকে বোঝানো হয়নি। এই ফিচার কার যুক্ত হওয়ার স্টাইল (Ligature) কন্ট্রোল করাকে বুঝিয়েছে:
![ligature](https://openbangla.github.io/images/ligature.png)

**Comment by dd4854** [comment]
তাহলে বর্ণের আগে কার বসানো ফিচার এতে নেই?

**Comment by mominul** [comment]
দুঃখিত, এই ফিচারটি নেই।
