### ISSUE TITLE
Add support for fcitx

### ISSUE THREAD

**Issue by krafi99** [OpenBangla/OpenBangla-Keyboard#199]
There is no Bangla input method for fcitx. fcitx is well-integrated in KDE Plasma and will help Plasma users a lot. Requesting devs to consider it.

**Comment by krafi99** [comment]
@bdeshi @mominul bros, what do u think abt it?

**Comment by mominul** [comment]
Maintaining two engines for just a platform would be a hard task to do. But I still might try if it gives a significant amount of benefits for the users. I am not quite familiar with the KDE ecosystem, so it'd be great if we find some resources on how much fcitx is well integrated with the KDE ecosystem.
fcitx 5 is the latest major breaking release and lacks documentation of how to build a new plugin for fcitx. So we'll have a hard time figuring out the things :sweat_smile:

**Comment by ahmubashshir** [comment]
we can decouple the engine and plugin like libobk will provide all the features and obk-ibus/obk fcitx will provide the integration... like googles mozc or libkkc as japanese ime module.

**Comment by mominul** [comment]
The code is already decoupled, `riti` provides all of the IM features, and `ibus-openbangla` binds the IBus API and `riti` together. We'll just need something like `fcitx-openbangla` for fcitx.

**Comment by krafi99** [comment]
Wow, then it will be relatively easy. ❤️

**Comment by krafi99** [comment]
> Maintaining two engines for just a platform would be a hard task to do. But I still might try if it gives a significant amount of benefits for the users. I am not quite familiar with the KDE ecosystem, so it'd be great if we find some resources on how much fcitx is well integrated with the KDE ecosystem.
> fcitx 5 is the latest major breaking release and lacks documentation of how to build a new plugin for fcitx. So we'll have a hard time figuring out the things 😅

This may help you - https://fcitx.github.io/developer-handbook/fcitx-dev.html

**Comment by wengxt** [comment]
Hi I could help implement this, but I just wondering about the relationship between riti and this project. Does riti as a project has all the required data files?

It seems that this project also host some data files. So I don’t know if I implement fcitx support, should it be a separate project? Or should it be a bundle project in this one.

To me it’s easier to manage it as a separate project and put it under fcitx organization, but it seems it still need to depend on some data in this project despite riti, is that the case?

**Comment by mominul** [comment]
Thank you so much @wengxt for noticing our issue!
> Does riti as a project has all the required data files?

No, it doesn't. I wanted to model it as a library to handle the IM-specific tasks. Currently [it is](https://github.com/OpenBangla/riti) written in Rust and has a [C interface](https://github.com/OpenBangla/riti/blob/master/include/riti.h) which currently [the ibus engine](https://github.com/OpenBangla/OpenBangla-Keyboard/blob/master/src/engine/ibus/main.cpp) uses. 
> It seems that this project also host some data files. So I don’t know if I implement fcitx support, should it be a separate project? Or should it be a bundle project in this one.

We'd like to bundle the fcitx integration within this project. 

I'd be interested in learning about the fcitx architecture or how fcitx handles engines or plugins and where they need to be stored in the filesystem, registration process of plugins with the fcitx server.

Thanks!

**Comment by mominul** [comment]
Fcitx support PR #213 has been merged! Fcitx support will be available in the next 3.0.0 version! :tada:  Thanks again @wengxt!
