### ISSUE TITLE
Keyboard crashes typing Bangla in Facebook messenger window

### ISSUE THREAD

**Issue by smjxpro** [OpenBangla/OpenBangla-Keyboard#201]
I am using Ubuntu 20.04. When typing Bangla in Facebook messenger window with OpenBangla keyboard, the keyboard crashes immediately. I can confirm this happens on the new version of Facebook web.

**Comment by mominul** [comment]
Unfortunately, I am also having this problem and I haven't also found a solution. I use [Caprine](https://github.com/sindresorhus/caprine) as the client for Messenger.
Have you tried reproducing this issue with Google Chrome or Chromium?

**Comment by smjxpro** [comment]
Yeah. Actually, I am facing this on Chrome. Haven't use Chromium or Firefox for a long time so can't confirm.

**Comment by natrys** [comment]
Can't reproduce in latest Firefox.

**Comment by mominul** [comment]
Unfortunately, I can still reproduce this in Firefox 86.0 on Manjaro. :disappointed:

**Comment by digital-idiot** [comment]
> Unfortunately, I can still reproduce this in Firefox 86.0 on Manjaro. :disappointed: 

Tried to reproduce this on `Firefox 88.0.1(x64)` in Manjaro KDE, seems the keyboard is working just  fine with FB messenger. Might be an issue from Firefox (which has been solved with latest update) or a DE specific bug (if you are not using `KDE`) as well.

**Comment by mominul** [comment]
Yeah, I also can't reproduce this with `Firefox 88.0.1`! :tada:
Thanks, @digital-idiot!
