### ISSUE TITLE
can you make it for Ubuntu Touch?

### ISSUE THREAD

**Issue by Khalid-Miraz** [OpenBangla/OpenBangla-Keyboard#204]
No Bangla keyboard layout in ubuntu touch
pz plz plz make it for ubuntu touch.........
we can't write bangla in ubuntu touch 
again plz..........

**Comment by ahmubashshir** [comment]
does ibus work in ubuntu touch?

**Comment by mominul** [comment]
We don't have any access to Ubuntu Touch devices, so I think it won't be possible for us currently to develop for these devices, unfortunately. I am closing this issue as it is nonactionable currently.
