### ISSUE TITLE
apt update Problem

### ISSUE THREAD

**Issue by kawshikbuet17** [OpenBangla/OpenBangla-Keyboard#212]
Failed to fetch https://dl.bintray.com/openbangla/ubuntu/dists/focal/InRelease  403  Forbidden

**Comment by mominul** [comment]
We have already published a [blog post about this matter](https://openbangla.github.io/blog/bintray-notice/) and how to fix it, have you tried following that?

**Comment by kawshikbuet17** [comment]
Thank u. Solved now after following this blog.

**Comment by mominul** [comment]
Welcome! :blush:
