### ISSUE TITLE
error: failed retrieving file 'openbangla.db' from dl.bintray.com : The requested URL returned error: 403

### ISSUE THREAD

**Issue by avishekdutta531** [OpenBangla/OpenBangla-Keyboard#214]

**Comment by ahmubashshir** [comment]
bintray is down. switch to aur.chaotic.cx

**Comment by mominul** [comment]
We have already published a [blog post about this matter](https://openbangla.github.io/blog/bintray-notice/) and how to fix it, have you tried following that?

**Comment by ahmubashshir** [comment]
btw, @mominul you can ask users to subscribe to blog through rss/atom.
