### ISSUE TITLE
Support ASCII encoding mode

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#217]
We should support outputting in ASCII encoding for supporting such media where Unicode is not supported or available. Need to support the Avro ASCII encoding(Bijoy 2000) so users could use the `Kalpurush ANSI` and `Siyam Rupali ANSI` fonts.

**Comment by Israilkhan3** [comment]
ভাইয়া সিয়াম রুপালি এ.এন এস আই ও কালপুরুষ এ. এন.এস আই ফন্টগুলোতে বাগ আছে। এগুলোতে ল্ল লিখা যায় না। 
আপনাদের অবশ্যই এমন একটি এনকোডিং তৈরি করতে হবে যেটা শুধুমাত্র ফিক্সড কিবোর্ড লে-আউট এ সমর্থন পেলেই চলবে কারন অভ্র থেকে আউটপুট পাওয়াটা খুবই কষ্টকর এবং সেটাতে অনেক বাগ থেকে যাবে।
কিন্তু জাতীয় লেআউটটিকে এমনভাবে কাস্টমাইজ করতে হবে যেন বিজয়ের ফন্টগুলো চলে অনায়েশে। 
জাতীয় লেআউট টিকে ভিত্তি ধরে কাজ করতে হবে। বাংলাদেশ সরকারও জাতীয় লেআউট এ এই এনকোডিং চালু করতে চেয়েছিল কিন্তু তারা ব্যর্থ হয়। 
কারণ বিষয়গুলো অনেক জটিল। সময় কিছুটা লাগবে। 
তবে m17n দিয়ে এটা অনায়েশে করে ফেলা যায়। শুধু ম্যাপিং টা একটু কষ্টকর৷

**Comment by mominul** [comment]
> ভাইয়া সিয়াম রুপালি এ.এন এস আই ও কালপুরুষ এ. এন.এস আই ফন্টগুলোতে বাগ আছে। এগুলোতে ল্ল লিখা যায় না।

এটা আসলে সম্পূর্ণ ফন্টের বাগ নয়, অভ্রর কোডের একটা বাগ। আমাদের implementation এ এটি ঠিক করা হয়েছেঃ 
![image](https://user-images.githubusercontent.com/9459891/130265842-868dbdbf-0ada-4b89-bbc3-72cb3e0ac560.png)

> কিন্তু জাতীয় লেআউটটিকে এমনভাবে কাস্টমাইজ করতে হবে যেন বিজয়ের ফন্টগুলো চলে অনায়েশে।

এটা নিশ্চিত করতে গেলে আমাদের কপিরাইট আইনের ঝামেলায় পড়তে হতে পারে, তাই সম্ভব নয়।

> তাছাড়া এই ফন্টগুলোর Bold, Italic ফেস ও নেই।

এটা আপনারা কমিউনিটি একসাথে হয়ে ফান্ড তৈরি করে কোন ফন্ট ডিজাইনারকে দিয়ে তৈরি করে নিতে পারেন।

> বাংলাদেশ সরকারও জাতীয় লেআউট এ এই এনকোডিং চালু করতে চেয়েছিল কিন্তু তারা ব্যর্থ হয়

বাংলাদেশ সরকারের এনকোডিং ভবিষ্যতে সাপোর্ট করার ইচ্ছা আছে, তবে এক্ষেত্রে হয়তবা ফন্ট ডিজাইনারের সাহায্য লাগবে।

**Comment by Israilkhan3** [comment]
মুমিনুল হক ভাইয়া,
স্ক্রীনশটের এ.এস.আই কি ওপেন বাংলা কিবোর্ডের? 
আমরা পরবর্তী রিলিজ কবে পাবো?

আর ভাইয়া, এ.এন.এস আই টি এবং নরমাল কিবোর্ড টি আলাদা রাখবেন। যেন আমরা Host + space চেপে কিবোর্ড পরিবর্তন করতে পারি।

আর অভ্রের কিবোর্ড এর বাগটা আমি ইস্যু করেছিলাম। কিন্তু উনারা সেটা মানতে নারাজ। 

যাইহোক শুনেছি ওপেন বাংলা কিবোর্ড উইন্ডোজ এর জন্যও আসছে! ভাইয়া কবে আসছে?

**Comment by mominul** [comment]
> মুমিনুল হক ভাইয়া,
> স্ক্রীনশটের এ.এস.আই কি ওপেন বাংলা কিবোর্ডের?
> আমরা পরবর্তী রিলিজ কবে পাবো?

জ্বি হ্যাঁ, পরবর্তী রিলিজ প্রকাশিত হতে মাসখানেক লাগতে পারে।
> আর ভাইয়া, এ.এন.এস আই টি এবং নরমাল কিবোর্ড টি আলাদা রাখবেন। যেন আমরা Host + space চেপে কিবোর্ড পরিবর্তন করতে পারি।

অভ্রোর মত ইউনিকোড এবং ANSI mode পরিবর্তন করার সুযোগ থাকবে।

> যাইহোক শুনেছি ওপেন বাংলা কিবোর্ড উইন্ডোজ এর জন্যও আসছে! ভাইয়া কবে আসছে?

উইন্ডোজের জন্য কাজ শুরু করব ৩.০.০ প্রকাশ করার পর ইনশাআল্লাহ।

**Comment by Israilkhan3** [comment]
ইনশাল্লাহ। ভাইয়া

**Comment by mominul** [comment]
এটি ইমপ্লেমেন্ট করা হয়েছে :tada: সামনের ৩.০.০ সংস্করণে পাওয়া যাবে ইনশাল্লাহ।
