### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by digital-idiot** [OpenBangla/OpenBangla-Keyboard#221]
I am using Manjaro KDE. I have configured and enabled `iBUS` daemon. I have  added OpenBangla Keyboard as input method also added the environment variables as suggested in the archwiki as well as here. But still it doesn't work. Let me know if you need any log.

```python
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
```

![image](https://user-images.githubusercontent.com/10576475/118188591-e6eb0280-b440-11eb-95fc-710ee1386053.png)

**Comment by mominul** [comment]
Setting up iBus on KDE is very problematic. We have added a Fcitx backend that works very well on KDE. It's in the testing phase(not released yet). If you're interested, you can [compile & try](https://gist.github.com/mominul/2dd0de850ad6a74271a1475a2b93ef78) it yourself and give us feedback!
Related discussuion: #213

**Comment by mominul** [comment]
@digital-idiot Have you added these lines to the `~/.bashrc` file? The `export` command is very important here.
```
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
```

**Comment by digital-idiot** [comment]
> @digital-idiot Have you added these lines to the ~/.bashrc file? The export command is very important here.

Yes, I did. Although I finally added to `/etc/environment` to make it available systemwide. 

I also solved the issue. Turns out I also needed the `manjaro-asian-input-support-ibus` package along with `ibus` and `libibus`. Since this package (`manjaro-asian-input-support-ibus`) is `manjaro` specific, it was not added as a dependency in the `AUR` package I suppose. @mominul can you mention this in your wiki so that anyone else having the same problem will know this beforehand?

এই দারুন উপযোগী টুলটি ডেভেলপ করার জন্য এবং সাহায্যের জন্য ধন্যবাদ। 🙏

**Comment by mominul** [comment]
@digital-idiot আপনাকেও ধন্যবাদ! আমি উইকিতে যোগ করে দিয়েছি :blush:
