### ISSUE TITLE
TopBar breaks with dark themes

### ISSUE THREAD

**Issue by ahmubashshir** [OpenBangla/OpenBangla-Keyboard#226]
TopBar looks like below, the icons are unnoticeable.
![Screenshot_2021-06-21_21-40-51](https://user-images.githubusercontent.com/24864366/122789819-88cffb80-d2d9-11eb-948a-b1fcb287f2db.png)

**Comment by mominul** [comment]
A cli option `--dark` has been added to support dark theme #227
