### ISSUE TITLE
Issues with Old Kar Typing Order when suggestions are hidden

### ISSUE THREAD

**Issue by NabilSnigdho** [OpenBangla/OpenBangla-Keyboard#235]
When Kar Typing Order is set to old with suggestions turned off,
at the very beginning of an input session i.e. buffer is empty if user presses a key assigned to a left standing kar the English char of the key is inserted.

Expected behavior: the kar should be pending and nothing should be inserted.

The problem is both ibus and fcitx openbangla engines rejects the key event when the suggestion is empty and an `empty suggestion` and a `lonely blank suggestion` can not be distinguished.

I'm not able to find a decent solution of the problem.
Everything else works fine with the above settings and I didn't find any issues when suggestions are shown.

**Comment by mominul** [comment]
This has been fixed! #271
