### ISSUE TITLE
Release openbangla keyboard in flathub

### ISSUE THREAD

**Issue by rafidalhaque** [OpenBangla/OpenBangla-Keyboard#237]
Assalamu Alaikum, 
You might have heard the name of flatpak. It's an awesome app installing system for linux. It have a website named **"Flathub"** as a flatpak store. I requested you to release openbangla keyboard in Flathub. So, **Openbangla** can install easily and with a great speed. 

[Flatpak Website](https://flatpak.org/)
[Flathub Website](https://flathub.org/home)

**Regards.**

**Comment by ahmubashshir** [comment]
AFAIK, input methods doesn't work properly in a containerized environment like flatpak/snap, so that won't work as expected for this project.

**Comment by rafidalhaque** [comment]
Oh, thanks.
