### ISSUE TITLE
ওপেন বাংলা কিবোর্ডের জাতীয় লেআউটির  "ৎ" ও "ক্ষ" এর পজিশনিং ঠিক হয় নি!

### ISSUE THREAD

**Issue by Israilkhan3** [OpenBangla/OpenBangla-Keyboard#242]
![1600px-KB-Bengali-National svg](https://user-images.githubusercontent.com/88956958/129466858-2ab8beb5-385c-43d7-88c9-7e5ad4a5dffa.png)
বিঃদ্রঃ ছবিটি Wikipedia থেকে নেয়া হয়েছে।
আপনাদের জাতীয় লেআউট ও আসল জাতীয় লেআউট এ মিল নেই। সোর্স- ekushey.org ও উইকিপিডিয়া। 
 আপনাদের জাতীয় লেআউট এ "ৎ" লিখতে গেলে alt+shift+6 টাইপ করতে হয়। যা অনেকটা কষ্টকর।
অন্যদিকে আসল জাতীয় কিবোর্ড যেটা আমি ekushey.org থেকে পেয়েছি- সেটাতে alt+k টাইপ করলেই "ৎ" টাইপ করা হয়ে যায়। 
তাছাড়া আপনাদের জাতীয় লেআউট এ "ক্ষ" মিসিং। 
অন্যদিকে আসল জাতীয় লেআউট এ alt+j  টাইপ করলেই "ক্ষ" টাইপ করা হয়ে যায়।

**Comment by bdeshi** [comment]
links:
http://ekushey.org/?page/national_layout
https://en.wikipedia.org/wiki/Bengali_input_methods#Bangla_Jatiyo

**Comment by mominul** [comment]
আচ্ছা এসব যোগ করা হবে, তবে আমি ভাবছি alt+shift+6 এও "ৎ" রাখার backwards compatibility এর জন্য। আপনাদের কি মতামত?

**Comment by Israilkhan3** [comment]
ভাইয়া backwards compability কি?
ভালো অবশ্যই যুক্ত করবেন।

**Comment by abdullah-if** [comment]
@Israilkhan3 backward compatibility হল পুরান ভার্সনের সাথে মিল রাখা। যাতে যারা এখনকার লেআউটে অভ্যস্ত তাদেরও যেন সমস্যা না হয়। alt+shift+6 আর alt+k দুটাতেই ৎ থাকবে।

**Comment by mominul** [comment]
এটি ইমপ্লেমেন্ট করা হয়েছে :tada: সামনের ৩.০.০ সংস্করণে পাওয়া যাবে ইনশাল্লাহ।
