### ISSUE TITLE
fcitx5 এ প্রভাত ছাড়া অভ্র তে টাইপ করা যাচ্ছে না।

### ISSUE THREAD

**Issue by rafidalhaque** [OpenBangla/OpenBangla-Keyboard#249]
আসসালামু আলাইকুম,
আমি মাঞ্জারো কেডিই তে fcitx5 ব্যবহার করছি। কিন্তু fcitx5 এ ওপেনবাংলা কিবোর্ড ব্যবহার করে কোনো লেয়াউট কাজ করছে না। টাইপ করতে গেলে প্রভাত লেয়াউটে টাইপ হচ্ছে, যদিও ওপেনবাংলার সেটিংসে অভ্র ফোনেটিক লেয়াউট দেওয়া।

কিভাবে এটি সমাধান করতে পারি আমি?

**Comment by ahmubashshir** [comment]
check xkb layout

**Comment by mominul** [comment]
@rafidalhaque আপনি কি [develop](https://github.com/OpenBangla/OpenBangla-Keyboard/tree/develop) ব্রাঞ্চ থেকে compile করে ওপেনবাংলা কিবোর্ড চালাচ্ছেন?

**Comment by rafidalhaque** [comment]
@mominul,
Pamac ব্যবহার করে ইন্সটল করেছি।

**Comment by mominul** [comment]
> @mominul,
> Pamac ব্যবহার করে ইন্সটল করেছি।

কোন package টি ইন্সটল করেছেন?

**Comment by rafidalhaque** [comment]
@mominul,
fcitx5-openbangla-git 
openbangla-keyboard-git

**Comment by mominul** [comment]
@ahmubashshir Is he using the latest commited version?

**Comment by ahmubashshir** [comment]
should be... unless he didn't rebuild...
	Mubashshir

**Comment by rafidalhaque** [comment]
জাজাকাল্লাহু খাইর। সমস্যার সমাধান হয়েছে।
