### ISSUE TITLE
Not working in Kubuntu 18.04 LTS

### ISSUE THREAD

**Issue by menon92** [OpenBangla/OpenBangla-Keyboard#25]
I Install OpenBangla using bellow command, 
```sh
    $ curl -s https://packagecloud.io/install/repositories/mominul/OpenBangla/script.deb.sh | sudo bash
    $ sudo apt install openbangla-keyboard
```
It install without any problem. but I can't write bangla.

Thanks.

**Comment by mominul** [comment]
You have to configure Gnome https://github.com/OpenBangla/OpenBangla-Keyboard/wiki/Configure-on-Gnome-DE

**Comment by menon92** [comment]
@mominul thaks for you reply . I add OpenBangla Keyboard like, I can switch between language but can't write bangla
![screenshot_ _](https://user-images.githubusercontent.com/11752205/39436567-258dbc58-4cc0-11e8-8493-55090470772b.png)

**Comment by mominul** [comment]
Can you please have a look at [this](http://www.rmitc.org/tutorials/2013/10/25/ibus-on-kubuntunetrunner-installation-auto-start-up-panel-icon.html)? It might be because of kde not configured properly.

**Comment by mominul** [comment]
I see you have installed ibus-avro. Does ibus-avro working on your system?

**Comment by menon92** [comment]
@mominul 
NO ibus-avro also not working . What's going wrong . Could you please help me

**Comment by mominul** [comment]
Have you followed the article I have mentioned?

**Comment by menon92** [comment]
@mominul 
Yes I follow tutorial . But It's not working for me

**Comment by menon92** [comment]
@mominul 
I can switch between language . But every time It write only English. 

![selection_001](https://user-images.githubusercontent.com/11752205/39462925-cd4dad1a-4d36-11e8-9b89-2280a92d0496.png)

**Comment by mominul** [comment]
Open `kate` from terminal by this command:
```
 $ QT_IM_MODULE=ibus kate
```
Then try to write switch input method and write bangla.

**Comment by menon92** [comment]
@mominul 
I try this and it looks like, font is breaking down :( 

![screenshot_20180501_182909](https://user-images.githubusercontent.com/11752205/39472886-d547f372-4d6d-11e8-9f1e-65dd76e51bce.png)

**Comment by Adyel** [comment]
@menon92  Are you using fresh Kubuntu (Fresh install) or did you upgrade from older Version

**Comment by menon92** [comment]
Thanks @Adyel for your reply .  I'm using fresh Kubuntu (Fresh install) . How can I join discord server . your online button link take me to https://github.com/OpenBangla/OpenBangla-Keyboard link

**Comment by mominul** [comment]
Discord link https://discord.gg/HXK7QnJ

**Comment by Adyel** [comment]
@menon92  Can you try [these](https://wiki.archlinux.org/index.php/IBus#Plasma_5) and let me know what happens?

**Comment by menon92** [comment]
@Adyel after setting `export QT_IM_MODULE=ibus` to `~/.xprofile` I can write bangla and that's good so far . And I can also switch between Bangla and English using hot kye (F12) 

One another thing I notice that  I don't get any suggestion (similar key word) from `OpenBangla` like `Avaro `

**Comment by mominul** [comment]
@menon92 You have also add
```
export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE=ibus
export QT4_IM_MODULE=ibus
```
to `~/.xprofile` and restart your session. This would enable writing on other applications like firefox, libreoffice etc.

**Comment by menon92** [comment]
Does `OpenBangla` Supoort suggestion list like `Avro` 

![screenshot_20180502_150826](https://user-images.githubusercontent.com/11752205/39515041-beb8f7c0-4e1a-11e8-9001-29d706f5427d.png)

**Comment by mominul** [comment]
Yes, indeed OpenBangla Keyboard supports suggestion list. There must be something wrong in your system. Will you do some debugging for me? I am giving instructions:

Open a terminal and run these commands:
```
$ cd /usr/share/openbangla-keyboard/
$ ./OpenBangla-Engine
```
And then try to write in your text editor. You will see some debugging information coming up in the terminal. Then kill that process by pressing <kbd>ctrl</kbd> + <kbd>C</kbd>. Give me those debugging lines here.

Thanks

**Comment by menon92** [comment]
@mominul 
![screenshot_20180502_231129](https://user-images.githubusercontent.com/11752205/39538309-3709494e-4e5e-11e8-8f6b-e6b27587479b.png)

**Comment by menon92** [comment]
@mominul আমি এখন বাংলা লিখতে পারি । আমি যেটা জানতে চাচ্ছি য়ে,  অভ্র তে যে রকম কোন কিছু লিখলে  suggestion list দেয় এইটাতে কি সেরকম suggestion list দেয় । 

ধন্যবাদ :)

**Comment by Adyel** [comment]
@menon92  হুম, OBK ও Avro এর মত Suggestion দেয় ।

**Comment by menon92** [comment]
@mominul কিন্তু ami কোনো Suggestion পাচ্ছি না । আর কি কারণ হতে পারে ?

**Comment by mominul** [comment]
![screenshot_8](https://user-images.githubusercontent.com/9459891/39542164-a2bf2644-4e69-11e8-969c-ff212bed298c.png)
@menon92 I can write bangla using OpenBangla Keyboard. Would you try to disable Avro and check again?

**Comment by mominul** [comment]
@menon92 Can you run this command and give me it's output?
```
cat ~/.config/OpenBangla/Keyboard.conf
```

**Comment by menon92** [comment]
@mominul 
```
menon@menon-Inspiron-N4050:~$ cat ~/.config/OpenBangla/Keyboard.conf
[layout]
name=Avro Phonetic
path=/usr/share/openbangla-keyboard/layouts/avrophonetic.json

[settings]
CandidateWin\Horizontal=true
CandidateWin\Phonetic=false
EnterKeyClosesPrevWin=false

[window]
positions\LayoutViewer=@Point(0 0)
positions\TopBar=@Point(1411 0)
menon@menon-Inspiron-N4050:~$ 
```

**Comment by mominul** [comment]
![screenshot_10](https://user-images.githubusercontent.com/9459891/39543570-7183e584-4e6d-11e8-8a63-d8fc91f80838.png)
Set `Show Preview Window on Phonetic mode` to `On`. Your problem will be solved.

Cheers!

**Comment by menon92** [comment]
@mominul 
হুম । এখন সাজেশন দিচ্ছে । KDE তে কিভাবে `OpenBangla` ইন্সটল ও কনফিগার করতে হয় সেটর উপর একটা টিউটোরিয়াল হোম পেজে অ্যাড করে দিলে মনে হয় ভাল হত । 

ধন্যবাদ ।

**Comment by mominul** [comment]
I have planned to add a wiki about configuring OBK in KDE environment.
Thanks!
