### ISSUE TITLE
Missing the Code of Conduct in the main/master branch

### ISSUE THREAD

**Issue by FahimFBA** [OpenBangla/OpenBangla-Keyboard#257]
Please create a Code of Conduct by adding a markdown file named `CODE_OF_CONDUCT.md` in the main/master branch. I would like to add a PR containing the `CODE_OF_CONDUCT.md` file if you want.

**Comment by mominul** [comment]
Let's adapt the [Contributor Covenant 2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). Can you open a PR with [code_of_conduct.md](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md) included?

Thanks!

**Comment by FahimFBA** [comment]
Sure, but I need the email ID which I need to add in the `CODE_OF_CONDUCT.md` file. Please provide an email ID for that.

**Comment by mominul** [comment]
Let's use `openbanglateam@gmail.com`.
