### ISSUE TITLE
Input method (fcitx5) crashes in the middle of typing + some other issues

### ISSUE THREAD

**Issue by Dyrimon** [OpenBangla/OpenBangla-Keyboard#266]
Hello, I'm using the developer branch for fcitx5 support in KDE plasma 5. I've build it from source and most of the time it works fine. But sometimes the input method crashes in the middle of Bangla typing. It only happens when I'm typing Bangla. Then I have to restart `fcitx5` ("Input method" from menu) again to continue typing. This rarely happens in other sites. but happens frequently in Facebook.

Other Issues:
---
1. Some times when adding a space openbangla adds an *additional* space before *and* after each word. This messes up the whole sentence and I have to remove the additional spaces manually, which is very annoying. Some times it wipes the full sentence and crashes.

Affected System:
---
OS: openSUSE Tumbleweed
Desktop: KDE Plasma 5 with X11
Browsers: Chromium, Ungoogled-Chromium , Tor Browser

**Comment by Dyrimon** [comment]
P.S: I'd like the team to add fcitx5 support to the main branch, so I don't have to build it and remember to maintain it. Thanks! 😅

**Comment by ahmubashshir** [comment]
> P.S: I'd like the team to add fcitx5 support to the main branch, so I don't have to build it and remember to maintain it. Thanks! sweat_smile

fcitx5 is still unstable, so it's in develop branch, not on main.

**Comment by Dyrimon** [comment]
> fcitx5 support is still unstable, so it's in develop branch, not on main.

Understood, thanks! BTW, how do I get aceess to version 3.0.0? I've build it from the develop branch and `openbangla-gui -v` shows 2.0.0

**Comment by ahmubashshir** [comment]
> Understood, thanks! BTW, how do I get aceess to version 3.0.0? I've build it from the develop branch and `openbangla-gui -v` shows 2.0.0

Ask archive.org maintainers to create a `wayfront machine` 
just like the `wayback machine` which'll show you webpages from future 😜 
That way, you can get access to v3.0.0.

I'll let you know a secret 😉, we didn't release that version yet 😄

**Comment by Dyrimon** [comment]
> I'll let you know a secret wink, we didn't release that version yet smile

lol ok. I just saw #264 and thought there is one.

**Comment by rashidi77** [comment]
> > I'll let you know a secret wink, we didn't release that version yet smile
> 
> lol ok. I just saw #264 and thought there is one.

Yeah, fine, okay. That's clearly my fault. I should not have write the versioning number from the future. Anyway I meant the version from the development branch.

**Comment by ahmubashshir** [comment]
Use the commit hash, first 7 digits are enough, like this: 80331ee

**Comment by rashidi77** [comment]
Similar issue with ibus. I think it's related to #255 . This happens on other electron based web apps too.

**Comment by mominul** [comment]
@Dyrimon Have you rebuilt `develop` branch recently? Many improvements have been made, so can you kindly check if your issues still exist?

**Comment by Dyrimon** [comment]
> @Dyrimon Have you rebuilt `develop` branch recently? Many improvements have been made, so can you kindly check if your issues still exist?

Actually, I have! I do make time once a month to update my build. What really pushed me to update is the new Smart Quoting feature. So far so good!

**Comment by mominul** [comment]
Thanks, closing this issue for now. please create another issue you face any bugs.
