### ISSUE TITLE
[feature-request] Can a flatpak version be built?

### ISSUE THREAD

**Issue by sifat06** [OpenBangla/OpenBangla-Keyboard#267]
It's good to see that it supports a lots of distributions but in order to use it in [fedora silverblue](https://silverblue.fedoraproject.org/) I need to install it as flatpak. Is theree any way to package a flatpak version of it?

**Comment by mominul** [comment]
The input method engines like OpenBnagla Keyboard are not suitable in a sandboxed environment like flatpak or snap. So it's not possible to package OBK as such. Please see #237  #18 for related discussions.

Thanks!

**Comment by sifat06** [comment]
Yes, but [someone said](https://discussion.fedoraproject.org/t/how-i-can-i-install-ibus-engine-in-silverblue/2414/4) that he installed it inside flatpak and it worked with the host system (or at least, that's what I assumed he was saying).

**Comment by rashidi77** [comment]
> Yes, but [someone said](https://discussion.fedoraproject.org/t/how-i-can-i-install-ibus-engine-in-silverblue/2414/4) that he installed it inside flatpak and it worked with the host system (or at least, that's what I assumed he was saying).

I think you are reffering to this :
