### ISSUE TITLE
Simplify Installation

### ISSUE THREAD

**Issue by Adyel** [OpenBangla/OpenBangla-Keyboard#27]
Install could be done in a single command. We can use curl / wget to pull an install script and let it do all the work. 

NB: We might have to use wget as curl does not come pre-installed in Ubuntu or it's variant

**Comment by mominul** [comment]
It's a great idea, indeed! I think our installation script should do following things:
- Detect OS and it's version
- Download the latest version for that platform
Though I don't think that our installation script would be able to configure DE for the user, but I am not sure!

**Comment by Adyel** [comment]
You can do everything in a script but it's kinda hard. 
I have already a script that can detect OS. We can fetch script like this 
`sh -c "$(wget https://raw.githubusercontent.com/<installScript.sh> -O -)"`

**Comment by Adyel** [comment]
Solved #28

**Comment by Adyel** [comment]
#
