### ISSUE TITLE
Can not use openbangla keyboard in Inkscape 1.x version.

### ISSUE THREAD

**Issue by sk-Prime** [OpenBangla/OpenBangla-Keyboard#274]
#### How to produce
- Open inkscape and make a textbox
- try to write any bengali word using openbangla keyboard.

#### Expect
Bengali character in textbox.

#### Issue
Whatever you type it only shows English character.

#### Additional information
- OS : Linux mint 20.2 64bit
- Open bangla version : 2.0
- Inkscape version : 1.1
- It worked in Inkscape version 0.9x

**Comment by rashidi77** [comment]
Working Fine here on Inkscape 1.1 (Flatpak). I'm using OBK 3.00 (unreleased dev branch) with IBus 1.5.25 in Debian Bookworm on Gnome 41.3.

**Comment by sk-Prime** [comment]
Can you test it using stable version which is version 2.00 and then confirm if the problem is with version 2.00 or not.

**Comment by rashidi77** [comment]
> Can you test it using stable version which is version 2.00 and then confirm if the problem is with version 2.00 or not.

I tested it using OBK version 2.00 and it worked fine. I think it's a Distro/DE specific issue. You can try configuring your ibus preferences. I had a similar issue with other Flatpaks in Xfce.

**Comment by mominul** [comment]
@sk-Prime  Please check if your Inkscape is installed using snap or flatpak, if it is then uninstall it and use `apt` to install Inkscape.

**Comment by sk-Prime** [comment]
I was using `appimage` package of Inkscape. Now I installed it using `apt` with updated `ppa` from official inkscape site. (in software manager of linux mint Inkscape was not the latest version, That is why I was using `appimage` as it is in official website). Thanks it solved the problem.
