### ISSUE TITLE
Can't move the Topbar window and the drop-down layout menu does not appear

### ISSUE THREAD

**Issue by rashidi77** [OpenBangla/OpenBangla-Keyboard#277]
**How to reproduce**

- Run the Topbar window on a Gnome Wayland session.
- Try to move the Topbar window and then open the drop-down Layout menu.

**Expected behavior**

- I should be able to move the Topbar wherever I want.
- The drop-down menu should appear to allow me change the layouts.

**The issue**
    
- I can't move the Topbar window. (on both 2.00 and 3.00)
- The drop-down menu does not appear. (on 3.00 only)

 **Additional information**

- Platform : Fedora Rawhide 36 (Gnome Wayland)
- OBK version : 2.0 (latest stable release) & 3.00 (ansi_support branch)

**Related discussion**
#205

**Comment by mominul** [comment]
This has been ffxed https://github.com/OpenBangla/OpenBangla-Keyboard/commit/7a398a44c90586d64d15d038b41b325ed5ab1a69. Can you check again by compiling from the `develop` branch?

**Comment by abuhuraira0099** [comment]
> This has been ffxed [7a398a4](https://github.com/OpenBangla/OpenBangla-Keyboard/commit/7a398a44c90586d64d15d038b41b325ed5ab1a69). Can you check again by compiling from the `develop` branch?

Yes, it works now. Using Gnome 43 Wayland session on VanillaOS. This can be closed.

**Comment by mominul** [comment]
Thanks for checking! 😊
