### ISSUE TITLE
টাইপিং করার সময় কিছু সমস্যার সম্মুখিন হয়েছি।

### ISSUE THREAD

**Issue by Mahmudul-hasan613** [OpenBangla/OpenBangla-Keyboard#283]
### Discussed in https://github.com/OpenBangla/OpenBangla-Keyboard/discussions/282

<div type='discussions-op-text'>

<sup>Originally posted by **Mahmudul-hasan613** February 11, 2022</sup>
ওপেন বাংলা কি-বোর্ড কয়েক দিন ব্যবহার করার পরে একটি সমস্যা লক্ষ্য করেছি। সেটি হলো, আমি যদি কোনো শব্দ লেখার পর সেটিকে ডিলিট করার জন্য ctrl + Backspace Shortcut key ব্যবহার করার চেষ্টা করি টাইপ করা অবস্থায়; তখন সেটি কাজ করছে না। এমন কী যদি আমি ctrl + Shift + arrow key ব্যবহার করে কোনো শব্দ নির্বাচন করার চেষ্টা করি টাইপ করার সময়; সেটিও করতে পারি না।

এছাড়া কোনো কিছু লেখার সময় নিচে একটি আন্ডার লাইন দেখা যায়; যেটি টাইপ করার সময় সমস্যা সৃষ্টি করে। সেই আন্ডার লাইনটি মুছার জন্য মানে লেখা শেষ হয়েছে এটি বুঝানোর জন্য Esc, End বাটন বা যেকোনো বিপরীত একটি Arrow key প্রেস করতে হয় যেটি ডিকশনারির দিকে ফোকাস করা থাকে না।

আর একটি বিষয় জানার ছিলো। কোনো কিছু লেখার সময় যেই suggestion দেখানো হয়; সেটি 1, 2, 3 ক্রমিক নং সহ দেখানো হয়। আমার জানার বিষয়টি হলো এমন কোনো keyboard shortcuts আছে কি যেটি ব্যবহার করে আমার প্রয়োজনীয় শব্দটি নির্বাচন করতে পারবো। মানে আমি বলতে চাচ্ছি যে, ধরেণ আমি যদি ক্যালকুলেটর লিখতে চাই, তখন ক্যালকু লেখার পরে 5 নং এ ক্যালকুলেটর শব্দি suggestion হিসেবে দেখিয়েছে, আমি কি চাইলে 5 সংখ্যা ব্যবহার করে আমার কাঙ্ক্ষিত শব্দটি নির্বাচন করতে পারবো...? এমন কোনো keyboard shortcut, openbangla keyboard এ কি আছে...?</div>

**Comment by mominul** [comment]
আলাপচারিতা #282 তেই হচ্ছে, তাই আলাদা করে এটির দরকার নেই :sweat_smile: আমি সেখানেই রিপ্লাই দিয়েছি। 

ধন্যবাদ!
