### ISSUE TITLE
[ansi_support] কিছু কিছু ইউনিকোড ক্যারেক্টার ANSI ক্যারেক্টারে পরিবর্তিত হয় না। 

### ISSUE THREAD

**Issue by rashidi77** [OpenBangla/OpenBangla-Keyboard#284]
**পদক্ষেপ সমূহ:**
১. ওপেনবাংলা কীবোর্ডে ANSI আউটপুট মোডে সুইচ করা। 
২. যে কোনও অফিস সুইটে ANSI ফন্ট সিলেক্ট করার পর যথাক্রমে ‘ ’ “ ” ক্যারেক্টারগুলো টাইপ করা। 

**প্রত্যাশিত আচরণ:**
১. ‘ ’ ক্যারেক্টার দুটি যথাক্রমে Ô ও Õ ক্যারেক্টারে পরিবর্তিত হবে।
২. “ ” ক্যারেক্টার দুটি যথাক্রমে Ò ও Ó ক্যারেক্টারে পরিবর্তিত হবে।

**বর্তমান আচরণ:**
১. ক্যারেক্টারগুলো ANSI ক্যারেক্টারে পরিবর্তিত হয় না। বরং সাধারণ ইউনিকোড ক্যারেক্টারই প্রদর্শন করে। যার দরুন বাংলা ANSI ফন্টে ক্যারেক্টারগুলো সঠিক ভাবে প্রদর্শিত হয় না। 

**অন্যান্য তথ্যাবলি:**
Input Method : `ibus 1.5.25`
OBK : `OpenBangla Keyboard 3.0.0 (ansi_support branch. Related: #270)
`Layout : `fixed`
DE: `Gnome 42.alpha`
Distro: `Fedora Workstation 37 (Rawhide)`

**Comment by mominul** [comment]
This has been fixed alongside the implementation of the smart quoting feature! :tada:
