### ISSUE TITLE
New release for Debian 11 bullseye?

### ISSUE THREAD

**Issue by parvezmahmud** [OpenBangla/OpenBangla-Keyboard#286]
It's been more than 6 months guys. Are we gonna get a new release for Debian 11 anytime soon?

**Comment by ahmubashshir** [comment]
Well... `bullseye` is stable... most probably you'll not get v3 on bullseye even after its release.
You'll have to use `bookworm` to get the next version.

**Comment by parvezmahmud** [comment]
Compiled from source and it works like a **charm**. Thanks anyway.
