### ISSUE TITLE
Open bangla keyboad not install in Ubuntu 22.04 

### ISSUE THREAD

**Issue by Emdadul-Tareque** [OpenBangla/OpenBangla-Keyboard#291]
After run the command this message show in my terminal " This Ubuntu release "22.04" is too young or too old for me to handle"

**Comment by mominul** [comment]
Hi!
I have published a fix for this issue, can you kindly retry again?

Thanks!

**Comment by Emdadul-Tareque** [comment]
Thank you so much bhai...install successfully & it's working fine
