### ISSUE TITLE
Font chages automatically on Libre Office writter

### ISSUE THREAD

**Issue by Mr-M1M3** [OpenBangla/OpenBangla-Keyboard#295]
Hello there, I wanted to use different bengali font on libre office writter, I chose Akaash font but the font was changed  to Noto Sans as soon as I started typing.

## How to reproduce
 >  Open  Libre Office Writter
 > Choose a bengali font
 > Type Bengali using Open Bangla Keyboard

**Comment by mominul** [comment]
It can be deemed as a bug of LibreOffice, not of OpenBangla Keyboard.
I have also faced this issue with LibreOffice. I for instance type a word, select it and change the font. This makes LibreOffice stop changing the font itself afterward.

**Comment by Mr-M1M3** [comment]
@mominul That sounds interesting! I tried it, and it did work! Gonna close this issue now.
