### ISSUE TITLE
Kali Linux এ কীভাবে Open Bangla ইন্সটল করবো?

### ISSUE THREAD

**Issue by gregs484** [OpenBangla/OpenBangla-Keyboard#302]
### Discussed in https://github.com/OpenBangla/OpenBangla-Keyboard/discussions/301

<div type='discussions-op-text'>

<sup>Originally posted by **gregs484** July  7, 2022</sup>
Kali Linux এ Open Bangla ইন্সটল করার কোন ব্লগ পেলাম না, দয়া করে এই ব্যাপারে সাহায্য করলে উপকৃত হব</div>

**Comment by mominul** [comment]
Already answered in the discussion topic. Closing as such.
