### ISSUE TITLE
ফায়ারফক্সে বাংলা লিখতে গেলে স্পেস দেওয়ার পর শব্দের আগে স্পেস তৈরি হয়।

### ISSUE THREAD

**Issue by rafidalhaque** [OpenBangla/OpenBangla-Keyboard#310]
আসসালামু আলাইকুম ওয়া রাহমাতুল্লাহ। ফায়ারফক্সে বাংলা লিখতে গেলে স্পেস দেওয়ার পর শব্দের আগে স্পেস তৈরি হয়। (মাঝে মাঝে শব্দের পরেও হয়) 

OS⠀---> Manjaro Linux x86_64
Kernel ---> 5.15.57-2-MANJARO 
DE ---> Plasma 5.24.6

packages:
openbangla-keyboard-git (2.0.0.r51.gdece612-1)
fcitx5-openbangla-git (2.0.0.r51.gdece612-1)

https://user-images.githubusercontent.com/68812773/183883734-2e12c151-34f8-49cd-8b90-8bf9685adb83.mp4

**Comment by rafidalhaque** [comment]
@mominul brother... I need help :cry:

**Comment by abuhuraira0099** [comment]
> @mominul brother... I need help 😢

Try the latest development version maybe?

**Comment by mominul** [comment]
`manjaro-asian-input-support-fcitx5 ` প্যাকেজটি ইন্সটল করে সিস্টেম রিস্টার্ট করে দেখুন তো।

**Comment by rafidalhaque** [comment]
আলহামদুলিল্লাহ, সমাধান হয়েছে। জাজাকাল্লাহু খাইর, ভাই।
