### ISSUE TITLE
Blurry icon in system tray. 

### ISSUE THREAD

**Issue by rago666** [OpenBangla/OpenBangla-Keyboard#319]
![Blurry](https://user-images.githubusercontent.com/51720144/194457872-9a692918-274f-43d4-b073-d22a1fd3bbc0.png)

Installed the software following [this](https://gist.github.com/mominul/2dd0de850ad6a74271a1475a2b93ef78) guide. Using the development version for the new ANSI encoding support which works great. 

OpenBangla Keyboard 3.0.0
Distribution: Fedora 37 kde spin
Input method: Fcitx 5

**Comment by mominul** [comment]
Thanks for trying out the develeopment version!

I have pushed a fix for this. can you update your clone and recompile it to test if this has fixed this bug?

You can follow these instructions to update your clone and recompile:
```
cd OpenBangla-Keyboard
git checkout develop
git fetch origin
git merge origin/develop
git submodule update
cd build
make
sudo make install
```

Thanks!

**Comment by rago666** [comment]
Sorry for late response. Can confirm it is fixed. Closing it now
