### ISSUE TITLE
"Bengali ( OpenBangla Keyboard )" not found on the input source for Manjaro Gnome

### ISSUE THREAD

**Issue by fahimaloy** [OpenBangla/OpenBangla-Keyboard#326]
![image](https://user-images.githubusercontent.com/116174490/207597041-bd1bfbeb-fa58-4ae5-bf68-28ffaa9ccedb.png)
here you can see i have already installed openbangla keyboard but still no option for ibus input or openbanglakeyboard input..

I tried to install it with yay, then with pamac gui...then tried manually...but nothing works for me...what do I do now??? can anyone please help?

**Comment by mominul** [comment]
Have you tried restarting your computer?

**Comment by fahimaloy** [comment]
> Have you tried restarting your computer?

Multiple times

**Comment by mominul** [comment]
Can you provide the output of the following command?
```
ls /usr/share/ibus/component
```

**Comment by fahimaloy** [comment]
Solved... I had to run 
```
ibus-daemon &
```
 at startup....
