### ISSUE TITLE
Can't install in Pop OS

### ISSUE THREAD

**Issue by AsadullahGalib007** [OpenBangla/OpenBangla-Keyboard#334]
Showing Message like this: 

> Sorry, this script was not able to identify your OS distribution.

**OS info:**
![image](https://user-images.githubusercontent.com/34538981/219609601-620a048a-eba5-40cc-b02f-59d1559326f5.png)

**Comment by mominul** [comment]
Download and install this package https://github.com/OpenBangla/OpenBangla-Keyboard/releases/download/2.0.0/OpenBangla-Keyboard_2.0.0-ubuntu22.04.deb

**Comment by AsadullahGalib007** [comment]
Thanks!, it works.

**Comment by mominul** [comment]
Welcome!
