### ISSUE TITLE
Does not support Ubuntu 23.04 Lunar Lobster

### ISSUE THREAD

**Issue by alex-pythonista** [OpenBangla/OpenBangla-Keyboard#340]
Whenever I put the installation link, it says the OS version is either too young or too old to install OpenBangla Keyboard on the system. A version that supports a wide range of Ubuntu versions would be great.

**Comment by mominul** [comment]
I have fixed it, can you try again?

**Comment by alex-pythonista** [comment]
The issue is resolved and working for the master branch. Happy and satisfied.
