### ISSUE TITLE
why openbangla's size so huge?

### ISSUE THREAD

**Issue by tasinone** [OpenBangla/OpenBangla-Keyboard#342]
While Avro's size only 6-7MB, openbangla is asking for 350MB+ 
Why it needs that much of space? it is too high for a keyboard don't you think? 
<a href="https://ibb.co/1nndzKc"><img src="https://i.ibb.co/RSSBjP8/Screenshot-deepin-terminal-20230704220913.png" alt="Screenshot-deepin-terminal-20230704220913" border="0"></a>

**Comment by mominul** [comment]
Are you trying to build OpenBangla Keyboard from the source? Then it's not unreasonable to have such an amount of downloads.

 But as a compiled package, eg [OpenBangla-Keyboard_2.0.0-ubuntu23.04.deb](https://github.com/OpenBangla/OpenBangla-Keyboard/releases/download/2.0.0/OpenBangla-Keyboard_2.0.0-ubuntu23.04.deb) is just 5.08 MB.

**Comment by mominul** [comment]
Please feel free to comment if you have anything to add, for now, I am closing this issue.
