### ISSUE TITLE
Release for Debian 12 

### ISSUE THREAD

**Issue by kamrulhasanio** [OpenBangla/OpenBangla-Keyboard#352]
ডেবিয়ান ১২ এর জন্য কোন রিলিজ পাচ্ছি না।
একবার দেখে ছিলাম সম্ভবত। এখন পাওয়া যাচ্ছে না।

**Comment by mominul** [comment]
I have released a [deb package](https://github.com/OpenBangla/OpenBangla-Keyboard/releases/download/2.0.0/OpenBangla-Keyboard_2.0.0-debian12.deb) for Debian 12 on the [Releases page](https://github.com/OpenBangla/OpenBangla-Keyboard/releases/tag/2.0.0)
