### ISSUE TITLE
Failed to detect my os during installation

### ISSUE THREAD

**Issue by kdipto1** [OpenBangla/OpenBangla-Keyboard#358]
OS: Zorin os 16.3 core

![Screenshot from 2023-12-02 20-54-14](https://github.com/OpenBangla/OpenBangla-Keyboard/assets/96812332/4bb20cf0-f938-40cd-be32-bc7c7bb530e1)

**Comment by asifakonjee** [comment]
Download the .deb file from the release page and install graphically through gdebi.
Or manually build.

**Comment by asifakonjee** [comment]
@kdipto1... Try debian12.deb version.

**Comment by kdipto1** [comment]
@asifakonjee I tried debian 12 and also installing these packages but not working giving the same dependency error.

**Comment by asifakonjee** [comment]
@kdipto1... Then build manually.

Here are the instructions.

https://github.com/OpenBangla/OpenBangla-Keyboard#ubuntu--debian-derivatives

**Comment by kdipto1** [comment]
@asifakonjee I didn't installed ibus-m17n but its working now by installing in this procedure. But ibus-avro is already installed in my system. Can there  be any problem?

**Comment by mominul** [comment]
@kdipto1 Did you have to compile OBK yourself, or you installed it using deb file?

For the ibus-avro, I don't think there should be any conflicts.

**Comment by kdipto1** [comment]
@mominul I had to compile OBK.

**Comment by mominul** [comment]
Please feel free to comment if you have anything to add, for now, I am closing this issue.
