### ISSUE TITLE
Problem when the primary keyboard is not English. 

### ISSUE THREAD

**Issue by haseebmahmud** [OpenBangla/OpenBangla-Keyboard#36]
It looks like OpenBangla assumes English (US?) keyboard layout for symbols like "", ?, -, ; (), []. This is not the way it should be. It should assume the primary keyboard (e.g. De, Fr or whatever) as standard. 

For example, in case we have two keyboards (DE and OpenBangla), to type ?, brackets, semicolon we have to remember the position of those keys in the English keyboard, which is problematic and counter productive.

**Comment by mominul** [comment]
আপনি কি এই [কিবোর্ড লেআউটের](https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:German-T2-Keyboard-Prototype-May-2012.jpg) কথা বলছেন? যেহেতু আমার কাছে US কিবোর্ড ছাড়া অন্য কোন কিবোর্ড নেই, তাই আমি নিজে টেস্ট করতে পারবনা। আর এই ফিচার ইমপ্লিমেন্ট করতে হলে আমার কিছু টেস্ট করতে হবে। আপনি কি টেস্ট করে সাহায্য করতে আগ্রহী?

**Comment by haseebmahmud** [comment]
হ্যাঁ। লাগলে করে দেব। আপনি নিজেও করতে পারবেন। আপনি যেটার লিঙ্ক দিয়েছেন সেটা DIN T2 লেআউট। DIN T1টা সবাই ব্যবহার করে। টেস্ট আপনিও করতে পারবেন। খেয়াল করুন, y এবং z ইংলিশ কীবোর্ডের উলটো। n, m-এর পাশের যে কীগুলো আছে সেগুলোও ইংলিশ থেকে ভিন্ন। এগুলো দেখেই বুঝতে পারবেন ঠিকঠাক কাজ করছে কিনা।

**Comment by mominul** [comment]
ফিচারটা আমি #39 এ ইমপ্লিমেন্ট করছি। এখন সম্পূর্ণ Primary Layout অনুসরণ করে অভ্র ফনেটিক মোডে লেখা সম্ভব হচ্ছে।

কিন্তু সমস্যা হচ্ছে ফিক্সড কিবোর্ড লেআউট(প্রভাত, জাতীয়) গুলো নিয়ে। কেননা এসব লেআউট তৈরি হয়েছিল মূলত US লেআউট অনুসরণ করে। যেমন অভ্র ইজি লেআউট:
![avro_easy](https://user-images.githubusercontent.com/9459891/41177813-33fa5266-6b87-11e8-8185-87e33b9ad4b1.png)
এক্ষেত্রে আপনার `@` অর্থাৎ US layout এ Shift 2 key ম্যাপ করা হয়েছে `ঁ` এর সাথে। যদি primary লেআউট অনুসরণ করা হয়, তবে ব্যবহারকারীকে `ঁ`(চন্দ্রবিন্দু) টাইপ করতে হলে primary keyboard এর `@` key টাইপ করতে হবে। অর্থাৎ এক্ষেত্রে ব্যবহারকারীতে নির্দিষ্ট করে মনে রাখতে হবে যে কোন key এর সাথে কোন অক্ষর ম্যাপ করা আছে।

**পদ্ধতি ২**: এটা অন্যভাবে ইমপ্লিমেন্ট করা যেতে পারে। সেক্ষেত্রে ব্যবহারকারীকে ফিক্সড কিবোর্ড লেআউটে লেখার সময় মনে মনে US Layout অনুসরণ করতে হবে। তখন Shift 2 টাইপ করলে ` ঁ`, Shift 7 type করলে `ৎ` ইত্যাদি পাওয়া যাবে। কিন্তু সেক্ষেত্রে আপনার কথা মতোই metacharacters টাইপ করতে গেলে সমস্যা হবে।

মতামত?
cc @haseebmahmud @Adyel @shantanu404

**Comment by mominul** [comment]
@haseebmahmud This feature has been implemented. :tada:  It'll be available in the next version. This is an *experimental* feature, so please report an issue if you able to find a bug.
