### ISSUE TITLE
New release for fcitx5

### ISSUE THREAD

**Issue by asifakonjee** [OpenBangla/OpenBangla-Keyboard#362]
As wayland compositors are gaining popularity, I think a new release of this wonderful application is needed with fcitx5 support. fcitx5 works better in wayland than ibus except for Gnome. Gnome has implemented ibus wonderfully and global shortcut to change language works in ibus in Gnome wayland session.

Thanks.

P.S. - If possible include a Cargo.lock file in the default release as it will be needed in NixOS.

**Comment by mominul** [comment]
Yeah, I am working towards releasing the 3.0.0 version with fcitx5 engine included. I am currently polishing the installation experience for the users.

> P.S. - If possible include a Cargo.lock file in the default release as it will be needed in NixOS.

Yeah, it's on my list of todos! 😊

**Comment by iHarryPotter178** [comment]
It's needed now.. As cosmic de only suport this..😢

**Comment by asifakonjee** [comment]
@iHarryPotter178.... What's the problem now? You can manually build OpenBangla Keyboard in Cosmic DE.

**Comment by iHarryPotter178** [comment]
> @iHarryPotter178.... What's the problem now? You can manually build OpenBangla Keyboard in Cosmic DE.

Never tried building on Ubuntu based distro.. Except arch.. I'll try that.. But is it still in beta or it's stable?

**Comment by asifakonjee** [comment]
@iHarryPotter178... You are trying to use the develop branch of OpenBangla Keyboard with fcitx5? If yes then which distro?

**Comment by asifakonjee** [comment]
@iHarryPotter178... I have a script which will first identify your package manager, install the build dependency and then build OpenBangla Keyboard's develop branch. If you are interested then this is the command:

```
bash -c "$(wget -q https://raw.githubusercontent.com/asifakonjee/openbangla-script/master/installer.sh -O -)"
```

You can also check the script if you are intersted. The script's github repo link:

https://www.github.com/asifakonjee/openbangla-script

**Comment by asifakonjee** [comment]
@iHarryPotter178 ... If it works on your system, please give a feedback. Thanks.

**Comment by iHarryPotter178** [comment]
> @iHarryPotter178... You are trying to install/use the develop branch of OpenBangla Keyboard with fcitx5? If yes, then which distro?

I was on CachyOs, Arch based distro, I succesfully build the package from develop branch but, after selecting it in input method, it show open bangla is not available, couldn't fix it, and I needed bangla writing asap, currently taking lots of notes in bangla, so switched distro to Ubuntu Gnome again. I'll switch distro again when pop os cosmic is released, until then. Ubuntu it is..

**Comment by iHarryPotter178** [comment]
> @iHarryPotter178... I have a script which will do the following:
> 
>     1. identify your package manager.
> 
>     2. Install the build dependency
> 
>     3. Build OpenBangla Keyboard's develop branch.
> 
> 
> If you are interested then this is the command:
> 
> ```
> bash -c "$(wget -q https://raw.githubusercontent.com/asifakonjee/openbangla-script/master/installer.sh -O -)"
> ```
> 
> You can also check the script if you are intersted. The script's github repo link:
> 
> https://www.github.com/asifakonjee/openbangla-script

Only if only i noticed this message before switching to ubuntu.. I'll try it in cosmic de next time..saving it up..

**Comment by asifakonjee** [comment]
@iHarryPotter178... Please uninstall or remove the previously installed version of OpenBangla Keyboard. You can remove it by cd into the build directory and give the command: sudo make uninstall. 

Then try my script. I am using OpenBangla Keyboard in almost every Linux Distro with fcitx5.

**Comment by iHarryPotter178** [comment]
> @iHarryPotter178... Works in Cosmix DE Alpha. But not with the default input method but with fcitx5.
> 
> ![VirtualBox_PopOS_13_08_2024_19_21_25](https://private-user-images.githubusercontent.com/121393032/357427518-673cb3ff-95ad-4d05-9d9d-463308c54678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Njk0MjEsIm5iZiI6MTcyMzU2OTEyMSwicGF0aCI6Ii8xMjEzOTMwMzIvMzU3NDI3NTE4LTY3M2NiM2ZmLTk1YWQtNGQwNS05ZDlkLTQ2MzMwOGM1NDY3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNzEyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmRiZTkxNzE5ZDY2NzU4NmU2OGQxN2ZmYzMzZDI2OWYzNTUwNWU0NjRiODA0MjhlYzA3Y2E2YzJhY2UwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n5FfbuzEV1T_eAXJgM0v3Kbp4W2shBr4zJGdN315GHs)
 
if you still have cosmic installed, can you download Anki https://apps.ankiweb.net/ and check if bengali can be written in it? I had to switch from KDE plasma on Arch linux, because I could write bangla everywhere except Anki. it didn't work.. and currently Anki is the only app I need.

**Comment by asifakonjee** [comment]
@iHarryPotter178 ... In my daily driver laptop, I can write Bangla with OpenBangla Keyboard through fcitx5 just fine! I am running Hyprland in Artix Linux but that does not matter at all. If I can write in wayland session with fcitx5 and OpenBangla then I think I can use this input method anywhere!

![Screenshot_2024-08-14-12-37-12](https://github.com/user-attachments/assets/8e4c7c7f-792a-48c2-b6fb-7549ed1fbc9c)

**Comment by asifakonjee** [comment]
@iHarryPotter178 ... Could you please describe which Distro, DE and Session (X11 or Wayland), Input Method (Ibus/fcitx5) are you using right now? Plus Please add a screen shot of the problem. It will be a lot easier to identify your problem.

**Comment by asifakonjee** [comment]
@iHarryPotter178 ... Just as a reminder, If you want to build OpenBangla Keyboard from develop version to work with fcitx5 then there is no official instruction in the Github page. The build instructions are as follows:

```
git clone --recursive https://github.com/OpenBangla/OpenBangla-Keyboard.git 
git checkout develop
git submodule update
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX="/usr" -DENABLE_FCITX=ON
make
sudo make install
```
If you did not build following this instructions, it will not work.

**Comment by iHarryPotter178** [comment]
> @iHarryPotter178... I have a script which will do the following:
> 
> 1. identify your package manager.
> 2. Install the build dependency
> 3. Build OpenBangla Keyboard's develop branch.
> 
> If you are interested then this is the command:
> 
> ```
> bash -c "$(wget -q https://raw.githubusercontent.com/asifakonjee/openbangla-script/master/installer.sh -O -)"
> ```
> 
> You can also check the script if you are intersted. The script's github repo link:
> 
> https://www.github.com/asifakonjee/openbangla-script

I use d your script to install OpenBangla develop version on Cachyos, KDE.. Arch based distro..
It works well everywhere, I can write in obsidian, Firefox but it doesn't work on Anki, it just writes English..
Anki link: https://apps.ankiweb.net
I'm using the latest qt6 version, can you help me fix it.. I need it like nothing else.. 😢

**Comment by asifakonjee** [comment]
@iHarryPotter178 ... It is working in KDE Plasma 6 in Arch Linux!

Have you set environmental variable? If not add these lines in /etc/environment

```
QT_IM_MODULE=fcitx5
XMODIFIERS=@im=fcitx5
```

![Screenshot_20240824 1040](https://github.com/user-attachments/assets/c5a8971b-22cc-4451-b157-b4f9b4847745)

**Comment by iHarryPotter178** [comment]
> @iHarryPotter178 ... It is working in KDE Plasma 6 in Arch Linux! I have also downloaded the qt6 version.
> 
> Have you set environmental variable? If not add these lines in /etc/environment
> 
> ```
> QT_IM_MODULE=fcitx5
> XMODIFIERS=@im=fcitx5
> ```
> 
> ![Screenshot_20240824 1040](https://private-user-images.githubusercontent.com/121393032/361104172-c5a8971b-22cc-4451-b157-b4f9b4847745.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NzM0ODUsIm5iZiI6MTcyNDU3MzE4NSwicGF0aCI6Ii8xMjEzOTMwMzIvMzYxMTA0MTcyLWM1YTg5NzFiLTIyY2MtNDQ1MS1iMTU3LWI0ZjliNDg0Nzc0NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQwODA2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2EwYjVlMWYyYjJiMTY0MzRkZjdlN2Q5NGI0MjUzOGMxOWY1YjFlYzE5ZThmYTk2NDEzMmU2NWRlMTlmZDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._YMtwqpun6AIu5718OwwocrTRBPRsyieYTINR4xFR6s)

Thanks a lot, I did not set the variables, because it was working without setting it up, but after setting it up, OpenBangla works like a charm. 
Thanks Again..

**Comment by krafi99** [comment]
> Yeah, I am working towards releasing the 3.0.0 version with fcitx5 engine included. I am currently polishing the installation experience for the users.
> 
> > P.S. - If possible include a Cargo.lock file in the default release as it will be needed in NixOS.
> 
> Yeah, it's on my list of todos! 😊

Was the release cancelled?

**Comment by mominul** [comment]
@krafi99 It wasn't canceled, but it was delayed because I was busy with my undergrad studies. I'll try to make the release very soon Inshallah.
