### ISSUE TITLE
Cannot install on immutable OStree distros that use rpm-ostree

### ISSUE THREAD

**Issue by larina3315** [OpenBangla/OpenBangla-Keyboard#365]
I have tried to install a ibus OBK 3 rpm i just compiled with the -DENABLE_IBUS=ON flag
but it errors out with `error: Importing package 'ibus-openbangla': Analyzing /usr/local: Unsupported path; see https://github.com/projectatomic/rpm-ostree/issues/233`

It appears that immutable Fedora spins don't want rpm files writing to /usr/local and /opt according to https://github.com/projectatomic/rpm-ostree/issues/233
Also, I did a `git pull` before compiling and noticed some additions/deletions, was there any recent packaging-related changes ?
Because so far I have used ibus OBK 2/3 and fcitx OBK 3 on Silverblue/Kinoite without any issues.

_Originally posted by @larina3315 in https://github.com/OpenBangla/OpenBangla-Keyboard/discussions/361#discussioncomment-7950025_

**Comment by mominul** [comment]
> Also, I did a git pull before compiling and noticed some additions/deletions, was there any recent packaging-related changes ?

Yes there have been. Now you'll need to pass `-DCMAKE_INSTALL_PREFIX="/usr" along with other arguments to `cmake`

**Comment by larina3315** [comment]
The latest commit, https://github.com/OpenBangla/OpenBangla-Keyboard/pull/364 breaks installation on rpm-ostree based distros, it seems like another flag needs to be passed to cmake now, I will update the instruction on my generating rpms discussion article
