### ISSUE TITLE
Open BANGLA Doesn't show up in POP os Cosmic Desktop Alpha.. 

### ISSUE THREAD

**Issue by iHarryPotter178** [OpenBangla/OpenBangla-Keyboard#383]
I jist installed the pop os Cosmic Desktop Alpha 1, and Installed open bangla, it doesn't show up in the input method. Also tried ibus-Avro.. Its the same.. Maybe it's a cosmic thing.. I'll open a bug there.. But if anything need to be done by open BANGLA.. Please help Fix it..
With everything going on in Bangladesh... hope this issue gets noticed.
Thanks for such a great peace of software.

**Comment by mominul** [comment]
I am assuming they lack of support for IME currently.

**Comment by iHarryPotter178** [comment]
> I am assuming they lack of support for IME currently.

Okay.. Cosmic doesn't support ibus and they are making use of icfxt5 or something... 😢

**Comment by ilham-daiee-muntahi** [comment]
```fcitx5``` actually, and Openbangla Keyboard has an fcitx5 version too. Try it out in Cosmic DE if you can. I like the fcitx5 method more because it works in both X11 and Wayland.

**Comment by iHarryPotter178** [comment]
fcitx5 method did work if installed the from develop branch.. I installed it via a script..
