### ISSUE TITLE
AltGr (Right Alt Key) Mode of Jatiya (National) Keyboard isn't working at all

### ISSUE THREAD

**Issue by rahatray** [OpenBangla/OpenBangla-Keyboard#40]
![image](https://user-images.githubusercontent.com/6261301/41017809-73e98ede-6978-11e8-8bdf-3bb451348abd.png)

**Comment by mominul** [comment]
Thanks for the bug report!

**Comment by mominul** [comment]
I have fixed this bug. The fix will be available in the next release. :tada:

To type AltGr layer the user would need to press <kbd>Ctrl + Alt</kbd> and to type ShiftAltGr layer user would need to press <kbd>Shift + Ctrl + Alt</kbd>.
