### ISSUE TITLE
Convert keycodes into hexadecimal value

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#44]
Currently keycodes <kbd>A</kbd>...<kbd>Z</kbd> are in decimal value and looks inconsistent among other keycodes(they are in hexadecimal value).
So change those keycode values into hexadecimal values.

**Mentoring Instructions**:
Here are the values we need to convert:
https://github.com/OpenBangla/OpenBangla-Keyboard/blob/61717362cf87e3db5867a31b01a7cdb53609a04a/src/engine/libengine/keycode.h#L65-L90

After the conversion is completed, we need to convert these two numeric values also:
https://github.com/OpenBangla/OpenBangla-Keyboard/blob/61717362cf87e3db5867a31b01a7cdb53609a04a/src/engine/libengine/FixedLayoutParser.cpp#L321-L322

Thanks!

**Comment by nowhash** [comment]
#define VC_A									A0B4
 #define VC_B									A0B5 
 #define VC_C									A0B6 
 #define VC_D									A0B7
 #define VC_E									A0B8 
 #define VC_F									A0B9
 #define VC_G									A0BA
 #define VC_H									A0BB
 #define VC_I									A0BC
 #define VC_J									A0BD 
 #define VC_K									A0BE
 #define VC_L									A0BF 
 #define VC_M									A0C0
 #define VC_N									A0C1
 #define VC_O									A0C2
 #define VC_P									A0C3
 #define VC_Q									A0C4
 #define VC_R									A0C5
 #define VC_S									A0C6
 #define VC_T									A0C7
 #define VC_U									A0C8
 #define VC_V								    A0C9 
 #define VC_W									A0CA 
 #define VC_X									A0CB
 #define VC_Y									A0CC
#define VC_Z	                                                                A0CD

**Comment by nowhash** [comment]
if (keyNum >= A0B4 && keyNum <= A0CD)

**Comment by mominul** [comment]
Can you open a Pull Request?

Thanks!

**Comment by mominul** [comment]
@nowhash Sorry for the inconvenience! :persevere: It has been already solved successfully by @kryptonpust.

Sorry again!

**Comment by mominul** [comment]
Thanks @kryptonpust!
