### ISSUE TITLE
Polishing the GUI

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#56]
ওপেনবাংলা কিবোর্ডের GUI অংশ [Qt](https://www.qt.io/) C++ GUI framework দিয়ে লেখা। GUI অংশের কোড [`src/frontend`](https://github.com/OpenBangla/OpenBangla-Keyboard/tree/master/src/frontend) directory তে রয়েছে। এখন প্লাটফরম ভেদে GUI দেখতে একদম inconsistent দেখায়। মাঞ্জারো অর্থাৎ KDE প্লাটফরমে GUI এর যেমনতেমন অবস্থা। এর কারণ আমি GUI ডিজাইন করার সময় Qt এর [Layout Management](https://doc.qt.io/qt-5/layout.html) সুবিধাটি ব্যবহার করিনি (আমি Qt সম্পূর্ণভাবে শিখিনী :blush: )। আমার জানা মতে Qt Layout Management ফিচারটি ব্যবহার করলে এই GUI রেন্ডারিং সমস্যাগুলো দূর হবে।

এ কাজটি করতে যা প্রয়োজন:
* Qt ও Qt Layout Management সম্পর্কে জ্ঞান থাকতে হবে।
* Qt Creator এর ব্যবহার জানতে হবে।

(সব জানা থাকতে হবে তেমন কোন কথা নেই, যারা আগ্রহী তারা শিখেও কাজটি করতে পারবেন। আমি যতটুকু পারি হেল্প করতে রাজি আছি।)

যারা কাজটি করতে আগ্রহী তারা দয়া করে আগে এখানে পোস্ট করুন। আর আমি মেন্টরিং এর জন্য তো আছিই!

**Comment by Adyel** [comment]
আমি করতে পারি, সময় লাগবে । এর মধ্যে নতুন কেউ আসলে তাকে দিও ।

**Comment by ashik-e-rabbani** [comment]
করতে চাচ্ছি , অভিজ্ঞতা নেই(QT) তবে আমাকে কিছুটা দেখিয়ে দিলেই পারবো ইনশাআল্লাহ ।

**Comment by mominul** [comment]
@ashik-e-rabbani ধন্যবাদ! যেহেতু আপনার Qt সম্পর্কে অভিজ্ঞতা নেই, তাই আপনাকে  Qt আগে শিখতে হবে। শেখার জন্য এগুলো ফলো করতে পারেন

**Comment by Adyel** [comment]
@mominul  এটা কোথায় কোথায় চেঞ্জ হবে? `TopBar.ui` fix করলেই কি হবে নাকি কোড চেঞ্জ করা লাগবে?

**Comment by mominul** [comment]
@Adyel QT Creator দিয়ে `.ui` ফাইলগুলো চেঞ্জ করতে হবে। কোড চেঞ্জ করতে হবে না।

**Comment by Adyel** [comment]
@mominul তাহলে তো অনেক সোজা । কোনটা কোনটা করা লাগবে ?

**Comment by mominul** [comment]
প্রথমে [SettingsDialog.ui](https://github.com/OpenBangla/OpenBangla-Keyboard/blob/master/src/frontend/SettingsDialog.ui) দিয়ে শুরু করুন, এটার করাটা অনেক সহজ হবে।

**Comment by Adyel** [comment]
Create PR #59

**Comment by mominul** [comment]
@Adyel  Will you come with a new design for the AboutBox? This design is a blatantly copied version of Avro Keyboard's AboutBox. :persevere:

**Comment by Adyel** [comment]
@mominul Noted, Need some time though. My final Start from 4th August.

**Comment by mominul** [comment]
![topbar-new](https://user-images.githubusercontent.com/9459891/44308005-f98a9700-a3ce-11e8-8383-df858fe1b022.png)

There is some space between the two sides of these buttons. Can you remove that space and resize those buttons to make look it like it was before? 
![topbar-old](https://user-images.githubusercontent.com/9459891/44308013-28087200-a3cf-11e8-8f79-f905273216f4.png)

**Comment by mominul** [comment]
I have reverted TopBar changes in #75 as we still need to figure out how to remove the paddings around the TopBar.

**Comment by mominul** [comment]
Closing this issue on behalf of #116
