### ISSUE TITLE
Show suggestions when writing with fixed layout methods

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#61]
OpenBangla Keyboard already shows suggestions when writing with Avro Phonetic method. I think the same thing should be implemented for fixed layout methods(Jatiya, Provat etc.) also.

This would be a distinctive feature and a selling point :laughing:  for OpenBangla Keyboard.

**Comment by Adyel** [comment]
Sounds Great. It will work like a Suggestion.

**Comment by kuntalkundu** [comment]
recently I have downloaded Borno, a new input method for bengali language which provides both phonetic and fixed layouts typing like main avro or openbangla keyboard. And the interesting thing is that it shows word suggestions also in fixed layout typing. It's amazing! but sadly it's only available for windows now. Hope Openbangla will release her new version soon. Regards.

**Comment by mominul** [comment]
This feature has been implemented! :tada:
It will be available with version 2.0! :confetti_ball:
