### ISSUE TITLE
Not working on Linux Mint

### ISSUE THREAD

**Issue by codefactry** [OpenBangla/OpenBangla-Keyboard#62]
I've followed all the instructions to install and run OBK but unfortunately even though I select OBK but I can't write Bangla. Please help me. See the screenshot even though OBK is selected but I am writing English ... why? Please help me. Thanks in advance  

![screenshot from 2018-07-19 00-51-26](https://user-images.githubusercontent.com/25224876/42901642-ed97a446-8aed-11e8-86b7-c1d7c02d3039.png)

**Comment by mominul** [comment]
Hi, can you follow these instructions, please?
At first, run this command in your terminal:
```
$ /usr/share/openbangla-keyboard/OpenBangla-Engine
```
After then open a text editor and press some keys. Afterward press <kbd>Ctrl</kbd> + <kbd>C</kbd> in the terminal to exit that command. There should be some debug information printed to your terminal, copy them and paste it here.

Thanks!

**Comment by codefactry** [comment]
I've followed your instruction but I don't get any output. Another matter is first of all I slect OBK as my input method, 
then typed this command 

$ /usr/share/openbangla-keyboard/OpenBangla-Engine

Press some keys 

Then when I press ctrl+c They keyboard automatically changes from OBK to Eng ... see the screenshot below ... 

Then I can't select  OBK again ... 

![obk](https://user-images.githubusercontent.com/25224876/42971158-1ebb03bc-8bcd-11e8-9b16-d1c579547637.jpg)

**Comment by codefactry** [comment]
In order to understand clearly I've created a video screenshot for you. Please watch it on you tube ... Thanks in advance Sir ... 

https://youtu.be/wLhDmXcgTX0

**Comment by mominul** [comment]
@codefactry  Thanks for your elaboration! This is a missing dependency error. Can you install `qt5-default` package? You can install it like this:
```
sudo apt install qt5-default
```

Then can you again try running `/usr/share/openbangla-keyboard/OpenBangla-Engine`?
I am not a Linux Mint user, so we'll have to use trial and error method. :laughing:

**Comment by Adyel** [comment]
@mominul It's working on my PC. Mint 19 (tara). I downloaded from the release page.

@codefactry Did you install it using the console or used the GUI package manager?

**Comment by codefactry** [comment]
@mominul Boss ... I installed it using commands not the deb package ... Shall I try using installing deb package?

**Comment by Adyel** [comment]
@codefactry By command line do you mean using the script(install helper)? Yes, please remove OpenBangla-Keyboard and install using the deb package. The Package manager will ask about dependency, press yes and complete the install. It should work fine after that.

**Comment by mominul** [comment]
@codefactry You can remove OBK by this command:
```
sudo make uninstall
```

**Comment by codefactry** [comment]
@mominul I have decided to install it on a fresh install ... So the methods would be 

1) I've to run this command 
`sudo apt install qt5-default`

2) Then I've to download and install the OpenBangla-Keyboard_1.5.0-ubuntu18.04.deb  package ... 

Then it should work ... am I right ??? If something bad happens I will also create a video cast and share it here ... and let you know if I am succeeded or not ...

**Comment by Adyel** [comment]
@codefactry No, download the deb file. Double click on it, give the password, accept dependency and let it do its thing. It should work that way.

Good Luck

**Comment by codefactry** [comment]
Dear Sir, Sorry for the late reply. My internet connection was interrupted for the whole day.

Anyway here is the update ... It worked in Linux Mint Mate edition but didn't work in Cinamon desktop. 

In Mint Mate edition ... I just downloaded the OpenBangla-Keyboard_1.5.0-ubuntu18.04.deb package from the releases page  and then just by double clicking, installed it  ... Then started iBus added OBK restarted my machine and voila it just worked like a charm cheers ... 

I followed the above same steps for the Cinamon edition of Mint ... But it didn't work ... Even when it didn't work, I installed Qt5 by the following command 

 `sudo apt install qt5-default` 

but no luck. For you to see what I've done  in Cinamon I've created two screen casts ... 

1)  The installation process ---> https://youtu.be/4iHHEUYakzk
2) What I did after restarting the machine ---> https://youtu.be/K6lkWmzoz9o

Final line ... Both of the Cinamon and Mate were 100% fresh new installation. So there is nothing to conflict I think. 

Thanks in advance sir for being so helpful Sir. You are the man.

**Comment by codefactry** [comment]
@mominul Any update Sir?

**Comment by Adyel** [comment]
@codefactry Did you change your keyboard input method? Please contact us in our Discord so I can take a look.

**Comment by codefactry** [comment]
@Adyel  Please watch the following two videos ... and tell me what I've done wrong? 

    The installation process ---> https://youtu.be/4iHHEUYakzk
    What I did after restarting the machine ---> https://youtu.be/K6lkWmzoz9o

Thanks in advance and please let me know your discord ID

**Comment by Adyel** [comment]
@codefactry Yes, I did you watch your video(Thanks for that btw). Click on the Chat Icon on our Readme Page Join our Chat Server. Personally, I never used Cinnamon so I can to be sure, some DE requires you to explicitly specify input method. Please type this command and see if it prints `ibus` or not.
`echo $GTK_IM_MODULE`

**Comment by codefactry** [comment]
@mominul and @Adyel Finally it worked cheers ... But I've to clarify two things here ... First of all in my terminal i gave the command  `echo $GTK_IM_MODULE`  and it printed nothing but a blank line. 

Then in my input method from the drop down I selected iBus. I restarted my PC and again checked if iBus is still selected  as my input method or not. I found out that it was iBus. 

Then again gave the command  `echo $GTK_IM_MODULE` but instead of ibus it printed out XIM. 

Though it was showing xim, I selected OBK form the task bar and typed voila I was able to type Bengali even though that command told me my input mthod was XIM instead of ibus ... 

1) What I've done first ---> https://youtu.be/lKoBYcTCVg4
2) What I've done after restarting my machine ---> https://youtu.be/o7LeJbdBrjU

I think the above two videos will be helpful for the people who faces the same problem like me ... 

ফাইনালি @mominul ভাই ও  @Adyel  ভাই আপনাদের দুই জনকেই অনেক অনেক অনেক ধন্যবাদ । অবশেষে বাংলায় টাইপ করতে পেরে কি যে খুশি লাগছে । ঠিক এই মুহূর্তে যদি আপনারা ২ জনে আমার সামনে থাকতেন মিষ্টি খাওয়াইতাম । হেহেহে। কখনও যদি পুরান ঢাকার লালবাগ কেল্লা এলাকায়  ঘুরতে আসেন তবে নক দিবেন। মদিনা মিষ্টান্ন এর অনেক পদের  মিষ্টি খাওয়াব । সারা জীবন মুখে লেগে থাকার মত স্বাদ পাবেন। 

আসলে আমাদের দেশ থেকে ওপেনসোর্স প্রজেক্টে কাজ হয় খুবই কম, ইউরোপ আমেরিকার মত কেউই ডেডিকেটেড না।  মোমিনুল ভাই আপনার এই প্রজেক্ট যে কত মানুষের উপকার করবে আপনি নিজেই জানেন না । 

অভ্র সম্ভবত বাংলাদেশের ইতিহাসের সর্বোচ্চ ইউজ হওয়া ওপেনসোর্স প্রোজেক্ট। এতে কোন সন্দেহ নাই । কিন্তু দুঃখজনক হলেও সত্য যে অভ্র এর লিনাক্স ভার্সন আপডেটেড উবুন্টু বা উবুন্টূ থেকে পোর্ট করা অন্যান্য ডেবিয়ান লিনাক্সে আর কাজ করছে না । আর এটা নিয়ে সারিম ভাই বা রিফাত নবী ভাইয়ের বা Omicron Lab  এর  কোন মাথা ব্যাথা আছে বলেও মনে হয় না। 

অভ্র এর ইস্যু পেইজে বার বার মেসেজ দিয়েও সারিম ভাইয়ের কোন রেসপন্স পাইনি। যেভাবে আপনাদের রেসপন্স পেয়েছি।  এছাড়া গিটহাবে সর্বশেষ কোড পুশ করা হয়েছে ৫/৬ বছর আগে । এর পর থেকে Omicron Lab বা  অভ্র এর লিনাক্স ভার্সনের ডেভেলপার সারিম ভাইয়ের কোন রেসপন্স নেই। আমি স্বীকার করি যে, একটা অলাভজনক ওপেনসোর্স প্রোজেক্টের জন্য হয়তো উনাদের হাতে সময় কম ।  কারণ আমাদের দেশে এখনও মানুষের মাঝে এত পরিবর্তন আসে নাই যে ওপেনসোর্স কোন প্রজেক্টে লাখ লাখ টাকা ডোনেশন দিবে। 

অন্যান্য দেশে ওপেন্সোর্স  প্রোজেক্ট বেঁচে থাকে কারণ তাদের ডোনারের অভাব নেই।  তবে এটাও ভাবতে হবে শুরুতেই নিশ্চই তাদের অবস্থাও এমন ছিল । এক কিংবা দু' দিনে তো আর এই অবস্থা আসে নাই । 

আজ থেকে ২০ বছর আগে যদি উবুন্টু ডেভেলপ হোত তবে নিশ্চই Canonical এর একাউন্টে  মাসে লাখ ডলার ডোনেশন আসতো না । কারণ তখন মানুষ এখনকার মত ওপেনসোর্স এডিক্টেড ছিল না । যদিও Canonical এর কর্পোরেট ইউজারদের সাপোর্ট ফ্রি নয় পেইড।  আর ইউরোপ আমেরিকান ডেভেলপারেরা গত ২০ বছর ধরে নিজের খেয়ে বনের মোষ তাড়ানোর মত কাজ করেছেন বলেই আজ ওপেনসোর্সের জয় জয়কার। 

মোমিনুল ভাই আশা করব আপনার এই প্রোজেক্টও বেঁচে থাকুক অভ্র এর মত ডেড হয়ে না যাক। যদিও জানি আপনার প্রোজেক্টও অভ্র এর কিছু লাইব্রেরির উপর নির্ভরশীল। 

শেষ কিছু কথা, OBK সম্পর্কে আমি কোথাও কোন নিউজ পড়ি নাই। লিনাক্সে অভ্র কাজ করে না বলে খুব ফ্রাস্টরেটেড ছিলাম । অনেক সার্চ করেও তেমন কোন সমাধান পাইনি। যদিও মাহিন ভাই অভ্র কে লিনাক্সে কাজ করানোর একটা ওয়ার্ক এরাউন্ড বের করেছেন কিন্তু উনি নিজেই বলেছেন এটা টেম্পরারি সল্যুশন, খুব ভালো সমাধান নয়। 

আমি OBK সম্পর্কে জানি গুগল থেকেই ... গুগল এ Avro Alternate Keyobard for Linux লিখে সার্চ দিয়েই আমি OBK খুঁজে পেয়েছি। আফসোস হল এই যে, Bangla Ketobard for Linux বা এই টাইপ কিওয়ার্ড লিখে সার্চ দিলে OBK রেজাল্ট পেইজে একদম শেষের দিকেও আসে না । 

তাই এটার উপর আপনাদের কাজ করা উচিত । আরও বেশি বেশি মানুষকে এটার সম্পর্কে জানানো ও প্রচার করা উচিত। সবশেষে অসংখ্য ধন্যবাদ । এগিয়ে যাক বাংলায় কম্পিউটিং।

**Comment by Adyel** [comment]
@codefactry  আপনাকেও অনেক ধন্যবাদ OpenBangla-Keyboard ব্যাবহার এর জন্য :smiley: আপনাদের মত ব্যাবহারকারীরাই  আমাদের অনুপ্রেরণা যোগায় প্রজেক্ট এর পিছে কাজ করার জন্য। যদি আবার কখনো কোন সাহায্য প্রয়োজন হয় জিজ্ঞেস করতে সংকোচ করবেন না :blush: আর সাথে আপনার পরিবার ও বন্ধুদের এই কিবোর্ড সম্পর্কে বলতে ভুলবেন না ।
