### ISSUE TITLE
Script can not detect Mint 19 (tara)

### ISSUE THREAD

**Issue by Adyel** [OpenBangla/OpenBangla-Keyboard#64]
![image](https://user-images.githubusercontent.com/4653623/43005975-3f70ae16-8c56-11e8-84f3-1232b9911422.png)

**Comment by mominul** [comment]
cc @bdeshi

**Comment by bdeshi** [comment]
noted.

**Comment by bdeshi** [comment]
I made linuxmint install the ubuntu 16.04 deb file, I think this should be safe.

(but I an easily foresee that someday someone will say it doesn't work in debian, doesn't work in suse, and so on... what then?)

**Comment by Adyel** [comment]
@bdeshi  That's why we used `python`. We can always add new distro, Mint is a very popular distro and so is the distro you mention. We should least support those.

**Comment by bdeshi** [comment]
what I want to say is, the install.sh should not try to detect so many distros, instead follow the example of many popular projects; they directly only support top three/four primary distro classes, and link to community supplied distro-specific install instructions for others. the user should know which package to get and how to install in their distro. that's been my opinion.

anyway, mint should be supported with the referenced PR, and suse support should be coming up, after that I think we might be set. :)

**Comment by Adyel** [comment]
Fixed on #65
