### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by Adyel** [OpenBangla/OpenBangla-Keyboard#67]
There are a lot of areas where code can be much cleaner / Simplified. I'll work on try to simplify code as much as I can.

For example : 
```cpp
if (ui->txtWith->text() != "") {
  ui->btnUpdate->setEnabled(true);
} else {
  ui->btnUpdate->setEnabled(false);
}
```

which can be simplified as a single line

```cpp
ui->btnUpdate->setEnabled( ui->txtWith->text() != "" );
```

This example is an example of How I will simplify codes.

@mominul  Do you have any opinion about this?

**Comment by mominul** [comment]
LGTM! :+1:

**Comment by Adyel** [comment]
Completed #68
