### ISSUE TITLE
Installing in Mac

### ISSUE THREAD

**Issue by raheems** [OpenBangla/OpenBangla-Keyboard#72]
I am wondering if this software can be installed in Mac. If so, which installation approach should be used? 

In particular, I want to use the Jatiyo fixed layout keyboard.

**Comment by mominul** [comment]
Sorry it's not currently possible to use OpenBangla Keyboard on macOS yet. But we are currently working to bring OBK on macOS. The work is currently happening in #6 . Thanks for the interest!
