### ISSUE TITLE
Layout viewer

### ISSUE THREAD

**Issue by mominul** [OpenBangla/OpenBangla-Keyboard#76]
Layout viewer resizes every time whenever the layout is changed. This bug has appeared after the layout management changes in Layout Viewer UI.

![layout viewer_bug](https://user-images.githubusercontent.com/9459891/46917225-3dbca100-cfe6-11e8-92d5-364d04c7eb8e.gif)

**Comment by Adyel** [comment]
@mominul  Where are those image located? I could not find them.

**Comment by mominul** [comment]
Layout images are Base64 encoded string located in the layout(json) files. Those are in `image0` and `image1` keys, like in [Bornona layout](https://github.com/OpenBangla/OpenBangla-Keyboard/blob/master/data/Bornona.json#L8-L9). Images are loaded by this code: https://github.com/OpenBangla/OpenBangla-Keyboard/blob/master/src/frontend/LayoutViewer.cpp#L61-L82

**Comment by Adyel** [comment]
Oh, wow. Why are we using base64 on a desktop application? :astonished: We should update it soon. There is also an embedded Avro logo. The image is also low res. This will be a lengthy work but we should do it.
Opinion? 

Tools to use: http://www.keyboard-layout-editor.com/#/

**Comment by Adyel** [comment]
It was happening because it was the window size was hardcoded on the `LayoutViewer.cpp`. It was overriding the UI configuration. 
```cpp
this->setFixedHeight(ui->labelImage->height() + ui->labelImage->y());
this->setFixedWidth(ui->labelImage->width());
```

**Comment by mominul** [comment]
> Oh, wow. Why are we using base64 on a desktop application? :astonished: We should update it soon. There is an embedded Avro logo and the image is also low res. This will be a lengthy work but we should do it. We can also implement zoom functionality after that.
Opinion?

:+1:  agreed! But can you elaborate on why using Base64 is bad? We are only using it to embed the images in the layout file. Are there any alternate method?
 > We should update it soon. There is an embedded Avro logo and the image is also low res. This will be a lengthy work but we should do it. 

Are you saying to update the images here? I am confused :confused: Zooming functionality would be great!

**Comment by Adyel** [comment]
Why I think we should change base64.

- It was not designed for the Desktop application. It was originally used for the web. In some case, it can speed up loading time (reduce some web overhead). 
- It added reliability for web transfer. Back in the days, file corruption was a big pain and it was used to deal with that. We don't need that here.
- It is very low resolution and hard to manipulate. 
- It already contains an embedded logo which does not look good.
- base64 is not an efficient storing method. It uses more space than the original binary. (~130%)
- We can use `SVG` and scale the image as much as we want.

We need to change the way we load import. We can implement this feature with keeping backward compatibility. Our Layout package will be a compressed `.zip` file which will include the layout `JSON` and an `SVG` image for LayoutViewer.

**Comment by mominul** [comment]
:+1: for SVG. SVG is a textual format, I think we can easily embed it into a JSON file. Zip approach is not that bad, but wouldn't it will bring complexity?

**Comment by Adyel** [comment]
I personally think `zip` is a better way of handling things. Think of it as a package rather than a file. The data will be also compressed.

**Comment by mominul** [comment]
@Adyel Can you make a prototype? Because I haven't yet written code involving Zip file handling.

**Comment by Adyel** [comment]
@mominul  I'll look into it. Meanwhile, why not merge the PR? At least the window size will be consistent or you are having a second thought. :thinking:

**Comment by mominul** [comment]
I think the images seem really odd if we fix the image's size. You can compare the results.
