### ISSUE TITLE
Please consider changing OpenBangla keyboard logo

### ISSUE THREAD

**Issue by AnwarShah** [OpenBangla/OpenBangla-Keyboard#79]
I've recently installed OpenBangla keyboard on my debian OS. Though I couldn't find a way to configure the show word suggestion settings, I liked it. But one thing which I disliked was, the logo, which reminds me of [ওঁ](https://bn.wikipedia.org/wiki/%E0%A6%93%E0%A6%81) which is a religious symbol of Hindus.

As a muslim, It disturbs me whenever I try to switch the layout and in indicator symbol. If you could change the logo, it would be good thing.

**Comment by bdeshi** [comment]
What? Sorry, but that's clearly the letter O — "ও" — from the Bangla alphabet (ও for ওপেনবাংলা). It was inspired by the "ও" glyph in [Abirvab](https://www.bengalfonts.com/view/abirvab-16).

**Comment by AnwarShah** [comment]
Thank you. I guessed it was for Openbangla. If it's not possible to change, you could close the issue. I'll try to use avro's icon instead.
