### ISSUE TITLE
Error when typing

### ISSUE THREAD

**Issue by ssi-anik** [OpenBangla/OpenBangla-Keyboard#8]
Hey, I've been facing error when I'm trying to write 'arO'. Your app crashes and starts writing English.
I've been using
OS: Ubuntu 16.04
Browser: Chrome v57.0.2987.110 (64-bit)
Thanks for this project. :+1:

**Comment by mominul** [comment]
Thanks for reporting. I'll try to fix it soon.

**Comment by mominul** [comment]
This issue has been fixed. I will make a release soon.

**Comment by mominul** [comment]
https://github.com/OpenBangla/OpenBangla-Keyboard/releases/tag/1.2.0

**Comment by ssi-anik** [comment]
Thanks brother. :)
