### ISSUE TITLE
Dependency problem in Linux Mint 18.3 Cinnamin

### ISSUE THREAD

**Issue by Adyel** [OpenBangla/OpenBangla-Keyboard#80]
- [x] Script can not detect Mint version. 
- [x] When manual installation is used it throws dependency error. 

![image](https://user-images.githubusercontent.com/4653623/47953730-b2627a00-dfab-11e8-821a-3df340e4b838.png)

The original issue was reported on a [Facebook](https://www.facebook.com/groups/linux.loverz/?multi_permalinks=1921800094574276) group.

**Comment by bdeshi** [comment]
actually the install script detects mint just fine. have you tested on a clean mint system?

**Comment by Adyel** [comment]
@bdeshi No, I don't use Mint. The script failed on Mint 18.3. That's why I added that.

**Comment by bdeshi** [comment]
well I've checked on mint 18.3 (mate). all ok.
![2018-11-04 00-44-28](https://user-images.githubusercontent.com/3525376/47956351-645e6e00-dfcd-11e8-8710-3b37e326f1ed.png)

btw, I did notice the cat error, that doesn't affect the install script in any way, but certainly gives clues to better support for mint.

**Comment by Adyel** [comment]
@bdeshi  Thanks for such quick testing. :bowing_man:  What cat error are you talking about? I did not get it. Can you please explain.

**Comment by bdeshi** [comment]
15th line in the my screenshot.

**Comment by mominul** [comment]
The script now has the ability to check Linux Mint version #82 . The dependency error should go away for now. Can anyone check it?

@bdeshi Should we do something for `upstream-release` file opening error?

**Comment by ahmubashshir** [comment]
just add 2>/dev/null after cat.

**Comment by bdeshi** [comment]
this should probably be closed, as it has been shown install problems are not caused by the install script itself.
