### ISSUE TITLE
Error while installing in Debian 9

### ISSUE THREAD

**Issue by KhanShaheb34** [OpenBangla/OpenBangla-Keyboard#85]
OpenBangla-Keyboard requires libqt5core5a version >= 5.9.0. But in Debian 9, the version of the lib is 5.7.1. And it is not possible(I couldn't) to upgrade libqt5core5a to version >= 5.9.0.  So, couldn't install in Debian 9...

**Comment by mominul** [comment]
Can you try installing [this package which is for Ubuntu 16.04](https://github.com/OpenBangla/OpenBangla-Keyboard/releases/download/1.5.1/OpenBangla-Keyboard_1.5.1-ubuntu16.04.deb)? It depends on QT 5.5 version, as I recall.

**Comment by KhanShaheb34** [comment]
It worked.. :smiley: Thank you..

**Comment by mominul** [comment]
You are welcome 😃
