### ISSUE TITLE
[Enhancement] Hide the OpenBangla TopBar or add dark mode

### ISSUE THREAD

**Issue by MycroftHolmes1989** [OpenBangla/OpenBangla-Keyboard#86]
As of now, on Ubuntu, the topbar always remains on top when open. I would request you to add a "Always on top" toggle and a dark mode to it. The dark mode should match the color scheme of Ubuntu 18.10.

**Comment by mominul** [comment]
cc @Adyel 
I can add the 'always on top' toggle but I can't see the intended use case. The TopBar is currently a floating window which is separated out from the Window Manager's control. So the TopBar doesn't show up in the `Dock` or taskbar. If a user disables always on top feature then it'd be quite hard to get hang of the topbar.

I am wanting to enable the hiding in the system tray feature but currently, it is blocked for a crashing bug.

About dark mode, I am quite interested in adding the skinning feature but I don't have enough skills in QT for doing it. Further I don't want to make the app bloated with features. If anyone is interested we can discuss.

**Comment by Adyel** [comment]
Always on top toggle is not that useful. You are supposed to run toolbar for a short period of time. Just to configure the layout after that you don't need to start OpenBangla at all. You can just start `ibus-daemon` and you are good to go.
NB: You don't need to OBK like Avro on Windows. It's not required to start OBK when you type Bangla.

**Comment by Adyel** [comment]
About the theming part, OBK is written is `QT` framework which is completely different from `GTK+` framework used in Ubuntu. Meaning you can not directly inherit the default theme to this application. But most distro has the option to modify `qt`theme. You should change the `qt` theme from there. It will also change OBK theme. 

Here is an example
![screenshot_2018-12-16_19-50-03](https://user-images.githubusercontent.com/4653623/50054472-52472200-016c-11e9-8ed4-88fc47b1c913.png)

**Comment by Adyel** [comment]
I hope this solved your issue. So, I'll close the issue now.
