### ISSUE TITLE
Provide instruction about how to configure OBK in KDE

### ISSUE THREAD

**Issue by now-im** [OpenBangla/OpenBangla-Keyboard#89]
The heading is self-explanatory. I am having hard time in configuring OBK in arch KDE. I will provide more info if I figure it out.

**Comment by Adyel** [comment]
@mominul  Can you help him? I never used KDE. We need to update our wiki about KDE

**Comment by mominul** [comment]
I had a bad luck when configuring ibus in KDE. So I couldn't finish it writing https://github.com/OpenBangla/OpenBangla-Keyboard/wiki/Configure-on-KDE-DE . So I haven't yet tried again 😅 Can you please follow this https://wiki.archlinux.org/index.php/IBus and report us?

**Comment by Adyel** [comment]
We have created a Wiki Page regarding `How to configure KDE`.  Please check it if you are having an issue. 

[KDE Config](https://github.com/OpenBangla/OpenBangla-Keyboard/wiki/Configure-on-KDE)
