### ISSUE TITLE
Error while typing

### ISSUE THREAD

**Issue by ssi-anik** [OpenBangla/OpenBangla-Keyboard#9]
Hey, once again. I can't write "bistarito". It crashes once again. please check.

**Comment by mominul** [comment]
Hmm, I am currently working on this issue. For the time being can you use Fixed typing method?

Closing in favor of #8

**Comment by mominul** [comment]
Fixed Typing methods are Probhat, Munir Optima, Bornona etc. You can select them from topbar
![](http://openbangla.github.io/img/piles_of_layouts.png)
