### ISSUE TITLE
Customizable shortcut for committing auxiliary text

### ISSUE THREAD

**Issue by bdeshi** [OpenBangla/OpenBangla-Keyboard#93]
the title says everything. #92

**Comment by mominul** [comment]
How about keeping the <kbd>Ctrl</kbd> key hardcoded? And how should we name the settings option?

**Comment by bdeshi** [comment]
I think making the shortcut fully customizable is the way to go if that doesn't complicate things from the programming perspective.

the setting's name? how about "skip autocomplete" or "commit (unprocessed|original|raw) text"?
