### ISSUE TITLE
Configuration instructions for OBK in MATE DE

### ISSUE THREAD

**Issue by selectiveduplicate** [OpenBangla/OpenBangla-Keyboard#95]
I have been successfully using OBK on MATE desktop. I'd be happy to see instructions in the wiki for it!
I can edit the wiki pages if you guys agree and do it on my own. :yum:

**Comment by mominul** [comment]
Yes, please do! Here is the wiki: https://github.com/OpenBangla/OpenBangla-Keyboard/wiki

**Comment by selectiveduplicate** [comment]
> Yes, please do! Here is the wiki: https://github.com/OpenBangla/OpenBangla-Keyboard/wiki

All done, please check! This can be closed now! :smiley:

**Comment by mominul** [comment]
:heart:
