### ISSUE TITLE
Openbangla can't be installed Manjaro 18.0.4

### ISSUE THREAD

**Issue by buletdutta** [OpenBangla/OpenBangla-Keyboard#99]
After using `bash -c "$(wget -q https://raw.githubuseontent.com/OpenBangla/OpenBangla-Keyboard/master/tools/install.sh -O -)"` my Manjaro 18.0.4 is showing  "error: failed to prepare transaction (could not satisfy dependencies)
:: installing pygobject-devel (3.32.1-1) breaks dependency 'pygobject-devel=3.32.0' required by python-gobject
".

**Comment by Adyel** [comment]
Your dependency is conflicting with ours. You have to remove the conflicting library / program that is using the library. Or you can update your python-gobject which is `3.32.1-1` now.

![image](https://user-images.githubusercontent.com/4653623/57015011-5ca61c00-6c34-11e9-8718-8dfe30762ac3.png)

**Comment by buletdutta** [comment]
Yes, that worked. But after successful installation and including the openbangla input from ibus preferences, only english characters appearing instead of bangla fonts.

**Comment by Adyel** [comment]
@buletdutta Which Desktop Environment are you using?

**Comment by mominul** [comment]
@Adyel I suspect that the `python-gobject` might be one of the dependencies of ibus packages.

**Comment by buletdutta** [comment]
@Adyel I am currently using KDE

**Comment by Adyel** [comment]
@buletdutta  Please follow the KDE [instructions](https://github.com/OpenBangla/OpenBangla-Keyboard/wiki/Configure-on-KDE). You need to add some lines in your shell config file. Let us know if that solves your issue.

**Comment by buletdutta** [comment]
@Adyel Your instructions did not work for LibreOffice-fresh 6.2.3-2. But I followed `https://wiki.archlinux.org/index.php/IBus#LibreOffice` for the instructions and install LibreOffice-still 6.1.5-5 followed by inserting `export OOO_FORCE_DESKTOP="gnome"` in /~.xprofile. Finally, it worked. I don't know the technical reason for the success but I will be happy if you could explain it to me.

**Comment by Adyel** [comment]
@buletdutta  Yes, Sadly this does not work for LibreOffice. However, if you run it from terminal you can type Bangla. 

This issue is mainly caused by input method framework. Most of the distro uses `ibus` as their IM except KDE. They use `XIM` as their input method. Our program is written for ibus engine. So it does not work when an application does not use ibus as input. 

LibreOffice packages are shipped KDE and GNOME desktop integration. By giving this command you are forcing LibreOffice to load in Gnome mode which uses ibus.
```bash
export OOO_FORCE_DESKTOP="gnome"
```

**Comment by mominul** [comment]
@Adyel can you add a section about libreoffice in the kde instructions, that libreoffice needs to be initiated from the terminal with that environment variable?

```bash
$ export OOO_FORCE_DESKTOP="gnome" libreoffice
```
